### ISSUE TITLE
图片没有显示出来

### ISSUE THREAD

**Issue by Catherine0728** [zzhoujay/RichText#10]
我在布局里面：
  <zhou.widget.RichText
        android:id="@+id/tv_content_right"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginRight="@dimen/d10"
        android:layout_toLeftOf="@id/iv_avatar_right"
        android:gravity="right|center_vertical"
        android:maxWidth="@dimen/d350"
        app:zhou_default_height="@dimen/d50"
        app:zhou_default_width="@dimen/d50"
        android:layout_alignTop="@+id/iv_avatar_right"
        android:textColor="@color/white"
        app:zhou_errorImage="@drawable/icon_sentence_next"
        app:zhou_placeHolder="@drawable/icon_sentence_next"
        android:textSize="@dimen/text_size_27"/>

代码里面将本地资源转换为drawable的形式显示出来，但是没有看到相应的图片显示

**Comment by zzhoujay** [comment]
”代码里面将本地资源转换为drawable的形式显示出来“是什么意思？原则上图片的URL必须是由HTML中img标签的src指定
