### ISSUE TITLE
解析时不支持&nbsp空格

### ISSUE THREAD

**Issue by shinobu59** [zzhoujay/RichText#100]
富文本里有 &nbsp空格标签，解析时不能识别

**Comment by zzhoujay** [comment]
由于是用的系统API去解析的，而它又没有做这些操作，等我后面自定义个Html解析器才能做

**Comment by shinobu59** [comment]
好的大神，请问什么时候能搞定Html解析器

**Comment by zzhoujay** [comment]
寒假回家了估计在家效率不咋高，还有富文本编辑器要开发，估计得到三月份
