### ISSUE TITLE
和RxJava + Dagger2+Retrofit+Okhttp有冲突

### ISSUE THREAD

**Issue by yizuochengchi** [zzhoujay/RichText#101]
我用了最新的依赖之后 发现 项目在5.0一下的机型 网络请求报错。这个可能是什么原因呢？ 谢谢~

**Comment by yizuochengchi** [comment]
您好~ 你可以告诉我你是怎么设置图片加载时 设置图片宽高度的吗？ Picasso可以吗 谢谢

**Comment by zzhoujay** [comment]
1. 报错具体信息能发下吗？
2. 你说的宽高是指图片显示的宽高还是加载到内存的bitmap真实宽高？

**Comment by yizuochengchi** [comment]
师兄 加你QQ吧 我的是 183 180 8374。我指的是图片实际展示的宽高 bitmap 里面的真实宽高貌似是不能改的 我在给图片urlDrawable.setBounds(0, 0, screenWidth, height); 的时候发现 无效。有点费解。 多谢师兄~
