### ISSUE TITLE
如果app本身使用的Glide是不是可以不用compile 'com.zzhoujay.glideimagegetter:glideimagegetter:latest-version'这个包

### ISSUE THREAD

**Issue by micookie** [zzhoujay/RichText#104]
如果app本身使用的Glide是不是可以不用'com.zzhoujay.glideimagegetter:glideimagegetter:latest-version'这个包。
直接通过自定义的接口走Glide，这样会少导入一个包。
glideimagegetter里边楼主做了什么特殊的操作吗，不建议通过自定义接口去做？
谢谢~

**Comment by zzhoujay** [comment]
当然可以，只要实现ImageGetter接口就行了，那个包是我用Glide做的一个实现而已，只要能满足你的需求怎样的实现都是可以的
