### ISSUE TITLE
不能识别字体样式 颜色好像不对

### ISSUE THREAD

**Issue by yxyaxng** [zzhoujay/RichText#106]
"<p style=\"padding: 0px; margin-top: 0px; font-size: 14px; color: rgb(102, 102, 102); font-family: tahoma, arial, sans-serif; white-space: normal; text-align: justify; text-indent: 0em; margin-bottom: 25px; line-height: 1.5em; background-color: rgb(255, 255, 255);\"><span style=\"font-family: 微软雅黑, &#39;Microsoft YaHei&#39;; font-size: 16px;\">自古英雄出少年。</span></p>"

**Comment by zzhoujay** [comment]
因为系统的HTML解析器没做这部分处理，后面自定义HTML解析器做出来后应该就可以解决了
