### ISSUE TITLE
Gif无法播放

### ISSUE THREAD

**Issue by passionli** [zzhoujay/RichText#107]
使用Demo中GifActivity无法播放，看了下没有执行
`            if (holder.isAutoPlay()) {
                resource.setCallback(this);
                resource.start();
                resource.setLoopCount(GlideDrawable.LOOP_FOREVER);
            }
`
好像是ImageTargetGif并没有执行

**Comment by passionli** [comment]
需要调用者指定.imageGetter(new GlideImageGetter())

**Comment by passionli** [comment]
点击back返回上一个Activity之后重新打开GIF的页面，GIF不播放

**Comment by passionli** [comment]
`if (holder.getCachedBound() != null) {
            drawableWrapper.setBounds(holder.getCachedBound());
        } else {`
再次回来之后执行这个代码，导致gif没start

**Comment by zzhoujay** [comment]
`2.4.0`版本中为默认图片加载器增加了Gif图片播放的功能，你试试这个
