### ISSUE TITLE
貌似超链接没有占满一行时点击整行的位置都会触发

### ISSUE THREAD

**Issue by vvvSkip** [zzhoujay/RichText#108]

**Comment by zzhoujay** [comment]
额，这个现在没啥办法，要做到只点击文字才有效，需要准确的获取文字的坐标和点下去的额坐标，而系统并没有提供获取实际绘制后每个文字坐标获取的接口，现在自能通过系统提供的：获取点击位置最靠近的文本，所以现在只能做到功能可用，但要像浏览器那样只有点文字才触发现在还做不了，抱歉
