### ISSUE TITLE
你好！我用fromMarkdown显示数据 但是图片显示不出来

### ISSUE THREAD

**Issue by CallmeJeRrYHo** [zzhoujay/RichText#112]
你好！我用fromMarkdown显示数据 但是图片显示不出来RichText.fromMarkdown(r.getData().getArticle().getContent())
                                .placeHolder(R.drawable.picture)
                                .imageGetter(new GlideImageGetter()).into(mTvContentItem);
是那里没有设置好吗？

**Comment by zzhoujay** [comment]
有没有添加网络请求的权限？图片显示不出来有没有显示占位图？

**Comment by CallmeJeRrYHo** [comment]
有网络网络请求的 对 连占位图都不显示

**Comment by zzhoujay** [comment]
文本样式都显示出来了吧？用默认图片加载器有没有问题？

**Comment by CallmeJeRrYHo** [comment]
默认也是这样 占位图都不显示

**Comment by zzhoujay** [comment]
图片本身没问题吧？手机网络有没问题？

**Comment by CallmeJeRrYHo** [comment]
图片没问题 网络也没问题 在ios上可以显示图片 要不 楼主给个数据我试试

**Comment by zzhoujay** [comment]
那就用我这个README吧，我之前测试是没问题的

```
# RichText

> Android平台下的富文本解析器

* 流式操作
* 低侵入性
* 支持Html和Markdown格式文本
* 支持图片点击和长按事件
* 链接点击事件和长按事件
* 支持设置加载中和加载错误时的图片
* 支持自定义超链接的点击回调
* 支持修正图片宽高
* 支持GIF图片
* 支持Base64编码
* 自持自定义图片加载器

### 效果

![演示](https://github.com/zzhoujay/RichText/raw/master/image/image.jpg "演示")

_by zzhoujay_
```

**Comment by CallmeJeRrYHo** [comment]
![qq 20170215115352](https://cloud.githubusercontent.com/assets/17061503/22960065/0c802308-f376-11e6-9cbc-4a28ed4a3e48.png)
![screenshot_2017-02-15-11-54-48-735_com wenxikeji](https://cloud.githubusercontent.com/assets/17061503/22960085/2e05ff48-f376-11e6-802d-ae4fb27e96b0.png)

![qq 20170215115449](https://cloud.githubusercontent.com/assets/17061503/22960068/0ea9f910-f376-11e6-9ae8-96734767bd44.png)

还是不行 请问这样设置应该没有错吧

**Comment by CallmeJeRrYHo** [comment]
![image](https://cloud.githubusercontent.com/assets/17061503/23073802/9e76c260-f571-11e6-90e5-937f2a519137.png)
老哥还是不行 我下载的demo 吧 markdown注释的解开了 之后运行 mainactivity中就是不显示图片

**Comment by zzhoujay** [comment]
试过真机没？

**Comment by zzhoujay** [comment]
log有没有啥报错信息？

**Comment by CallmeJeRrYHo** [comment]
真机模拟器都试过了  公司的电脑和家里的电脑也试过了 网络没问题 加载HTMl格式的也没问题

**Comment by CallmeJeRrYHo** [comment]
没有报错 就是没有图片

**Comment by zzhoujay** [comment]
好的，我明天帮你看看，今天有事

**Comment by CallmeJeRrYHo** [comment]
好的好的 非常感谢 star先点了~

**Comment by zzhoujay** [comment]
你那边代码可以贴一下么

**Comment by CallmeJeRrYHo** [comment]
`package com.hjh.myapplication;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.TextView;
import android.widget.Toast;

import com.zzhoujay.richtext.RichText;
import com.zzhoujay.richtext.callback.OnUrlLongClickListener;

public class MainActivity extends AppCompatActivity {
    private static final String markdown_test = "image:![image](http://image.tianjimedia.com/uploadImages/2015/129/56/J63MI042Z4P8.jpg)\n[link](https://github.com/zzhoujay/RichText/issues)";
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        final TextView textView = (TextView) findViewById(R.id.text);
        RichText.fromMarkdown(markdown_test).clickable(true).urlLongClick(new OnUrlLongClickListener() {
            @Override
            public boolean urlLongClick(String url) {
                Toast.makeText(getApplicationContext(),url,Toast.LENGTH_SHORT).show();
                return true;
            }
        }).into(textView);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        menu.add(0, 0, 0, "RecyclerView");
        menu.add(0, 1, 1, "ListView");
        menu.add(0, 2, 2, "Gif");
        menu.add(0, 3, 3, "Test");
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if (item.getItemId() == 0) {
            startActivity(new Intent(this, RecyclerViewActivity.class));
        } else if (item.getItemId() == 1) {
            startActivity(new Intent(this, ListViewActivity.class));
        } else if (item.getItemId() == 2) {
            startActivity(new Intent(this, GifActivity.class));
        }
        return super.onOptionsItemSelected(item);
    }
}
`

![qq 20170219231517](https://cloud.githubusercontent.com/assets/17061503/23103696/3fc2a3e4-f6fa-11e6-8941-c0d19e3d01a6.jpg)

![qq 20170219231634](https://cloud.githubusercontent.com/assets/17061503/23103699/4652b6d6-f6fa-11e6-9a61-78670f431e6f.jpg)

**Comment by zzhoujay** [comment]
这个问题在`2.4.0`版本中修复了

**Comment by CallmeJeRrYHo** [comment]
好了 可以用了 非常感谢！！！！！
