### ISSUE TITLE
代码无法分行，且Gif 图无法正常播放

### ISSUE THREAD

**Issue by IamXiaRui** [zzhoujay/RichText#115]
1、代码是这样的格式：<code> ...</code> 只能显示一行，无法分块且无法滑动。

2.Gif 无法正常播放，已经做了如下处理，仍然无效：

// 设置为Html
                RichText.fromHtml(postBean.getContent()).autoFix(false).fix(new ImageFixCallback() {
                    @Override
                    public void onFix(ImageHolder holder) {
                        holder.setAutoFix(true);
                        if(holder.isGif()){
                            holder.setAutoPlay(true);
                        }
                    }
                }).into(mPostContentText);

**Comment by IamXiaRui** [comment]
代码是 <code >  标签

**Comment by IamXiaRui** [comment]
代码是 code 标签

**Comment by zzhoujay** [comment]
1. 目前code标签没做换行的处理，但是代码块是可以自动换行的
2. 默认的图片加载器目前不支持播放Gif图片，需要播放Gif图片可以使用[GlideImageGetter](https://github.com/zzhoujay/RichText/wiki/自定义图片加载器)

**Comment by zzhoujay** [comment]
在`2.4.0`版本中为默认图片加载器加入了对Gif图片播发的支持
