### ISSUE TITLE
2.4.0加载gif直接崩了 T T

### ISSUE THREAD

**Issue by PGYH** [zzhoujay/RichText#119]

**Comment by zzhoujay** [comment]
能把出错信息发下么？我这边测试没问题

**Comment by PGYH** [comment]
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 2810 (com.yh.yhnews)

也可能是我使用方式有问题  昨天刚换的2.4.0

**Comment by zzhoujay** [comment]
这个看不出任何问题啊，能把测试代码发下么

**Comment by PGYH** [comment]
`        
RichText.fromHtml(richArticle.content)
                .cache(CacheType.NONE).autoFix(false).fix(new SimpleImageFixCallback() {
            @Override
            public void onImageReady(ImageHolder holder, int width, int height) {
                holder.setAutoFix(true);
                holder.setAutoPlay(true);
                super.onImageReady(holder, width, height);
            }
        }).into(textContent);
`

**Comment by zzhoujay** [comment]
数据内容呢，也发下，测试机API level是多少
