### ISSUE TITLE
连续多张图片,上下滑动,点击事件错位

### ISSUE THREAD

**Issue by f-evil** [zzhoujay/RichText#12]
如题

**Comment by zzhoujay** [comment]
刚刚测试了下，并没有发现有错位的情况，你可以运行一下demo试试看看，我这边没有发现错位的情况

**Comment by f-evil** [comment]
可以试试这个

private static final String xxx="<html><body><img src='http://t2.easylinking.net:10010/yue/152*152_b5357961-ca58-4f42-b04f-891e63885e56.jpg' width='373' height='658' /><img src='http://t2.easylinking.net:10010/yue/152*152_d678f935-ac9d-40b8-85e5-ad45bdf60047.jpg' width='373' height='658' /><img src='http://t2.easylinking.net:10010/yue/152*152_74579e25-cd97-49b0-8899-b916d74b9a15.jpg' width='373' height='279' /><img src='http://t2.easylinking.net:10010/yue/152*152_04e88864-f3b0-47b4-84d2-a1e3656b6bb1.jpg' width='373' height='663' /><img src='http://t2.easylinking.net:10010/yue/152*152_fd6365c7-40d1-4ad9-a42a-4d1296078a53.jpg' width='373' height='279' /><img src='http://t2.easylinking.net:10010/yue/152*152_b6611b76-750f-4f49-b702-4835bcf39080.jpg' width='373' height='663' /><img src='http://t2.easylinking.net:10010/yue/152*152_ffad2ddf-cb9e-4964-8e44-242f3112d38a.jpg' width='373' height='663' /><img src='http://t2.easylinking.net:10010/yue/152*152_f31bf5e1-cdcf-4e79-bdbc-82983ed33e4d.jpg' width='373' height='663' /><img src='http://t2.easylinking.net:10010/yue/152*152_9a20db36-d7c9-47fd-88df-3d6042d7053a.jpg' width='373' height='663' /></body></html>";

**Comment by f-evil** [comment]
可以试试

http://223.202.31.66:10008/yueServer/activity/getSingleActivity.do?refActivityId=23c154e0-c55b-4da2-b8ab-4f7f183c4f65&refUserId=2043

这个链接下 desc字段下的html
然后打印一下看看,的确是重复的

**Comment by zzhoujay** [comment]
设置图片点击监听的那个回调方法里的那个List的各个item都是一样的么？

**Comment by f-evil** [comment]
很特别,
比如有1,2,3,4,5,6,7,8,9图片
我这儿的现象是,点击1,2打出来的地址是一样的(这个一直存在),有时候点击9地址是正确的,有时候打出来的是8地址

**Comment by f-evil** [comment]
发现问题了
因为<img>标签连重复出现
例如:
"<img></img><img></img><img></img><img></img><img></img><img></img>"
在每个标签之间价格换行标签或其他标签就不会有这种情况

**Comment by f-evil** [comment]
发现问题了
因为<img>标签连重复出现
例如:
"\<img\>\<\/img\>\<\img\>\<\/img\>\<\img\>\<\/img\>\<\img\>\<\/img>
在每个标签之间价格换行标签或其他标签就不会有这种情况
