### ISSUE TITLE
加载gif图片崩掉了

### ISSUE THREAD

**Issue by yxyaxng** [zzhoujay/RichText#120]
报错信息是 
Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering

richText 异常代码
com.zzhoujay.richtext.RichText.getDrawable(RichText.java:342)
2 com.zzhoujay.richtext.parser.CachedSpannedParser.handleImage(CachedSpannedParser.java:119)
3 com.zzhoujay.richtext.parser.CachedSpannedParser.parse(CachedSpannedParser.java:33)
4 com.zzhoujay.richtext.RichText.generateRichText(RichText.java:179)
5 com.zzhoujay.richtext.RichText.access$000(RichText.java:39)
6 com.zzhoujay.richtext.RichText$1.run(RichText.java:149)

我查询了一下这问题，
http://stackoverflow.com/questions/37108618/could-not-find-class-android-graphics-drawable-rippledrawable
我在api19的系统上会有问题
api21以上的系统不会报错。

**Comment by zzhoujay** [comment]
我用API17的模拟器测试没有问题，而且RichText库没有引用`RippleDrawable`相关的任何类啊，你把完整的报错截图给我看下吧，还有你测试的代码

**Comment by yxyaxng** [comment]
我测试了一下大牛你的代码，也是这样报错的
RichText.from(GIF_TEST).autoFix(false).fix(new SimpleImageFixCallback() {
            @Override
            public void onLoading(ImageHolder holder) {
                if(holder.isGif()){
                    holder.setAutoFix(true);
                    holder.setAutoPlay(true);
                }
            }
        }).into(textView);

**Comment by zzhoujay** [comment]
我在API17的模拟器、API19和24的真机测试都没有问题，你开一个新项目直接跑这段代码有问题没？
还有Android Studio的Instance Run最好关闭再试下

**Comment by goejgiel** [comment]
API19 真机 demo的GifActivity内容都没改
文件GifDrawable
运行到
                movie.draw(canvas, bounds.left, bounds.top);
没catch到报错，程序直接退出了
log是这句
Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering

**Comment by zzhoujay** [comment]
我这边也是用的GifActivity测试的，但是在API24真机测试没问题，API19的一个手机一个平板也没问题，API19和17的模拟器也没任何问题，你有试过别的设备没？在其他设备有问题没？模拟器呢？
讲道理我这个库没用到过`RippleDrawable`啊

**Comment by goejgiel** [comment]
19版本和24版本这个调用 Movie.draw 有差异，不知道是不是错误的原因

19

    public native void draw(Canvas canvas, float x, float y, Paint paint);
    
    public void draw(Canvas canvas, float x, float y) {
        draw(canvas, x, y, null);
    }
24

    private native void nDraw(long nativeCanvas, float x, float y, long paintHandle);

    public void draw(Canvas canvas, float x, float y, Paint paint) {
        nDraw(canvas.getNativeCanvasWrapper(), x, y,
                paint != null ? paint.getNativeInstance() : 0);
    }

    public void draw(Canvas canvas, float x, float y) {
        nDraw(canvas.getNativeCanvasWrapper(), x, y, 0);
    }

**Comment by zzhoujay** [comment]
就算有差异也不会有兼容性问题吧，有兼容性问题的话API会提示的吧，而且我这边的机器全都没出现问题啊，你那边机器全都有问题么？实在不行显示Gif图可以换GildeImageGetter
