### ISSUE TITLE
解析的内容包含<小于号会有问题

### ISSUE THREAD

**Issue by hnxylc8818** [zzhoujay/RichText#124]
如果加载的html片段是下面的这样：
`
设函数f(x)=cos(x+φ)(0<φ<π).若f(x)+f′(x)是奇函数，则φ=(    ).<br /><br /><br /><br /><br /><br />
`
加载之后，从"0<"这之后内容都显示不出来了，应该是把小于号<认为是一个标签开始，不知道有没有解决方法

**Comment by zzhoujay** [comment]
额，html的语法中`<`是需要通过转义的，具体转意参照[这个](http://tool.oschina.net/commons?type=2)，而且Html的解析是调用系统API实现的，然而系统也没有提供这类接口，你可以先把这些符号自己转义下在解析试下

**Comment by hnxylc8818** [comment]
这样确实可以，或者在< 小于号后面加个空格也可以正确解析，不过麻烦的是怎么区别当前这个<符号是小于号还是html标签的开始符号

**Comment by zzhoujay** [comment]
额，这个就只能你自己去做了，本来就是源文本自己的问题
