### ISSUE TITLE
在小米和其他手机上显示不全！

### ISSUE THREAD

**Issue by wl386123298** [zzhoujay/RichText#125]
布局文件：
`
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/coordinatorLayout"
    app:layout_behavior="@string/appbar_scrolling_view_behavior">

    <android.support.design.widget.AppBarLayout
        android:id="@+id/columnItemContentAppBarLayout"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:background="@color/white"
        android:clipChildren="false"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

        <android.support.design.widget.CollapsingToolbarLayout
            android:id="@+id/columnItemContentCollapsingToolBarLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:clipChildren="false"
            app:contentScrim="?attr/colorPrimary"
            app:expandedTitleTextAppearance="@style/TextAppearance.AppCompat.Title"
            app:layout_scrollFlags="scroll|enterAlwaysCollapsed|enterAlways"
            app:statusBarScrim="?attr/colorPrimary"
            app:titleEnabled="false">

            <ImageView
                android:id="@+id/columnItemContentImageView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:scaleType="centerCrop"
                tools:src="@mipmap/ic_launcher"/>

            <android.support.v7.widget.Toolbar
                android:id="@+id/columnItemContentToolBar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                app:layout_collapseMode="pin"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
                app:titleTextAppearance="@style/Toolbar.TitleText"
                />

        </android.support.design.widget.CollapsingToolbarLayout>
    </android.support.design.widget.AppBarLayout>

    <android.support.v4.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/toolbar"
        android:overScrollMode="never"
        android:scrollbars="none"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:padding="@dimen/dp_10">

                <com.mikhaellopez.circularimageview.CircularImageView
                    android:id="@+id/columnItemContentAuthImage"
                    android:layout_width="40dp"
                    android:layout_height="40dp"
                    android:layout_centerVertical="true"
                    app:civ_border="false"
                    tools:src="@mipmap/ic_launcher"/>

                <TextView
                    android:id="@+id/columnItemContentName"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="@dimen/dp_10"
                    android:layout_toRightOf="@+id/columnItemContentAuthImage"
                    android:textColor="#000"
                    android:textSize="14sp"
                    tools:text="title"/>

                <TextView
                    android:id="@+id/columnItemContentNameDesc"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="7dp"
                    android:layout_toRightOf="@+id/columnItemContentName"
                    android:ellipsize="end"
                    android:maxLines="1"
                    android:textColor="#999"
                    android:textSize="14sp"
                    tools:text="▶title"/>

                <TextView
                    android:id="@+id/columnItemContentNameHeadLine"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_below="@+id/columnItemContentName"
                    android:layout_marginLeft="10dp"
                    android:layout_marginTop="5dp"
                    android:layout_toRightOf="@+id/columnItemContentAuthImage"
                    android:textColor="#666"
                    android:textSize="13sp"
                    tools:text="这里是简介"/>

            </RelativeLayout>

            <View
                android:layout_width="match_parent"
                android:layout_height="1px"
                android:background="#ccc"/>

            <TextView
                android:id="@+id/columnItemContentTitle"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:padding="10dp"
                android:textColor="#333"
                android:textSize="18sp"
                tools:text="这里是标题"/>

            <TextView
                android:id="@+id/columnItemContent"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_toRightOf="@+id/columnItemContentAuthImage"
                android:lineSpacingExtra="2dp"
                android:padding="@dimen/dp_10"
                android:textColor="#555"
                android:textSize="14sp"
                tools:text="title"/>

            <TextView
                android:gravity="center"
                android:id="@+id/columnItemContentCreated"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="right"
                android:padding="@dimen/dp_10"
                android:textColor="#999"
                android:textSize="15sp"
                tools:text="创建于"/>

        </LinearLayout>
    </android.support.v4.widget.NestedScrollView>
</android.support.design.widget.CoordinatorLayout>
`
这样在小米和三星的6.x的手机上显示是这样的,如下：
![](http://i1.piimg.com/567571/631058ebde5d4c04.jpg)

**Comment by zzhoujay** [comment]
？
哪个TextView是用了RichText的？
你换个空Activity可以把段内容显示全吗？

**Comment by wl386123298** [comment]
id号为columnItemContent是用richText显示的！
初步发现是我设置setFitsSystemWindows导致的，我设置为false就可以了！有点奇怪

**Comment by zzhoujay** [comment]
显示不全是横向还是纵向显示不全？是不是TextView高度不够？把开发者模式中的显示布局边界边界打开看看

**Comment by wl386123298** [comment]
是纵向的，我设置textView的高度为match的，在布局中你也看到了！边界打开后textview的高度很小！

**Comment by zzhoujay** [comment]
TextView的高度是match的话就是和父布局一样高，也就是说是父布局的问题吧，感觉应该不是我这边的问题，你可以再自己研究下

**Comment by wl386123298** [comment]
问题解决，在NestedScrollView加上 android:layout_gravity="fill_vertical"就可以解决了！

**Comment by zzhoujay** [comment]
好的
