### ISSUE TITLE
使用textview显示markdown，滑动的时候有时候会闪烁，是要做什么特别设置吗？

### ISSUE THREAD

**Issue by yawin** [zzhoujay/RichText#126]
如题！

**Comment by zzhoujay** [comment]
是图片已经加载完成后滑动还是会有闪烁么？闪烁具体是个什么情况呢？

**Comment by yawin** [comment]
没有图片的情况也会有，固定textview的高度或者宽度，在滑动的时候出现。闪烁就是滑动的时候textview部分内容(有时候也会整个textview)背景颜色有变化，显示的内容字体出现淡红色的背景，类似于被选中的样子，继续滑动会显示正常。
发现当内容是xml或者代码（包含在```里的内容）或者有超链接（![]()）在里面的时候更容易出现.
测试的手机是三星 note 3，android4.4.2.
谢谢!

**Comment by yawin** [comment]
测试的东西是：md文件大概98行，textview固定高度300。当前页面就只有一个textview和一个button，button在textview上面。

**Comment by zzhoujay** [comment]
TextView外面有没有包裹一个scrollview呢？

**Comment by yawin** [comment]
没有包含，只存在一个LinearLayout，orientation = "vertical"

**Comment by yawin** [comment]
不好意思，不知道是谁把我的测试机那个界面刷新监控给开了，关掉后就没有问题了，谢谢！

**Comment by zzhoujay** [comment]
好的
