### ISSUE TITLE
为什么加载不出来gif

### ISSUE THREAD

**Issue by wufw1989** [zzhoujay/RichText#127]
RichText.fromHtml(content).cache(CacheType.NONE).autoFix(false).fix(new SimpleImageFixCallback() {

            @Override
            public void onImageReady(ImageHolder holder, int width, int height) {
                
                holder.setAutoFix(true);

                holder.setAutoPlay(true);

                super.onImageReady(holder, width, height);

            }

        }).into(tv);
content:
```
<img src="http://timage.wurener.com/uploads/image/201703/0c1e63958a1f.gif?e=1489481282&token=XUL0BZmLMSrc-xNPQS3J6EWoKmit9-C5NtjAK25b:3pZv1idT2SkrkCjlHaWFBxdKv_Y=" alt="" />
```
望作者大大讲解下,我的邮箱wufw1989@163.com

**Comment by zzhoujay** [comment]
是因为目前判断图片是不是gif是通过src的后缀名来判断的，你可以加一句`holder.setImageType(ImageHolder.ImageType.Gif)`试试

**Comment by wufw1989** [comment]
那如果像我这样 就不能动态判断了吗

**Comment by wufw1989** [comment]
作者大大,方便邮箱聊吗,或者实时通讯,我这边比较紧急,帮我下好吗?我邮箱wufw1989@163.com

**Comment by wufw1989** [comment]
作者大大,还是加载不出来,而且按照你的标签代码数据加载的话,就直接崩溃了,方便说下电话或者qq吗,我这边比较紧急.帮我下








在 2017-03-15 12:55:37，"郑州" <notifications@github.com> 写道：


是因为目前判断图片是不是gif是通过src的后缀名来判断的，你可以加一句holder.setImageType(ImageHolder.ImageType.Gif)试试

**Comment by yongsheng659** [comment]
大神们求助 为什么不能加载gif图片， 如果特别长的html 会很卡

**Comment by jiawei-i** [comment]
异步加载会好一点。

**Comment by yongsheng659** [comment]
我也写了 异步了 ，包括callback回掉，可是如果不into的话 回掉那都不会走 ，急求 怎么弄这，谢谢！

**Comment by zzhoujay** [comment]
@yongsheng659 麻烦新开个issue，调用into方法解析才会开始
