### ISSUE TITLE
为什么富文本里会自动多出好几个空行呢?

### ISSUE THREAD

**Issue by wufw1989** [zzhoujay/RichText#129]
有的是自动换行,但后面还有空格,有的是段落之间的空格太大,有的是文字与图片之间的空太大,作者大大有碰见过吗

**Comment by zzhoujay** [comment]
发个截图看看

**Comment by wufw1989** [comment]
![Uploading jieping.jpg…]()
你看看

**Comment by wufw1989** [comment]
在github上貌似没上传图片成功,邮件回复下,请求url为下面的
http://i.wurener.com/v4/image_show.json?&app_key=family_app&app_version=4.0.2&feedable_id=14&from_client=Android&sign=b56c0902d76937b442e71c38c76708c0&uid=10077








在 2017-03-21 12:40:36，"郑州" <notifications@github.com> 写道：


发个截图看看

**Comment by ghuiii** [comment]
问题解决了吗？现在也遇到同样的问题

**Comment by yuiopt** [comment]
padding问题，遇上div标签和p标签会有padding

**Comment by zzhoujay** [comment]
这个问题暂时解不了，是系统Html解析器的问题，目前也没有时间开发自定义的Html解析器，后面有时间了会去解决的
