### ISSUE TITLE
宽高问题

### ISSUE THREAD

**Issue by HumorSmith** [zzhoujay/RichText#13]
这个问题似乎还没解决.我
```
     htmlTv.setImageFixListener(new RichText.ImageFixListener() {
            @Override
            public void onFix(RichText.ImageHolder holder) {
                if (holder.getWidth() > 10 || holder.getHeight() > 10) {
                    int width = getScreenWidth(getApplicationContext());
                    int height = width;
                    holder.setWidth(width);
                    holder.setHeight(height);
                    holder.setScaleType(RichText.ImageHolder.CENTER_INSIDE);
                }
            }
        });

        htmlTv.setRichText(article.getContent());
```
效果还是没有占满一个频幕宽度。是我代码写的有问题?

**Comment by shaoyi1991** [comment]
我也遇到了该问题，holder.getWidth()返回－1，holder.getHeight()也是－1。
看看源码吧，得。估计没附上值。

**Comment by shaoyi1991** [comment]
private static Pattern IMAGE_WIDTH_PATTERN = Pattern.compile("width=\"(.*?)\"");
    private static Pattern IMAGE_HEIGHT_PATTERN = Pattern.compile("height=\"(.*?)\"");

必须富文本中有宽和高的标签才行啊。
能不能感觉图片大小自适应呢？

**Comment by zzhoujay** [comment]
能不能把你测试的html代码贴一下，我测试下 @shaoyi1991

**Comment by shaoyi1991** [comment]
<p>每天看你们发说说，我都好羡慕 。你们长得又好看 ，还用智能手机，又有钱，整天讨论一些好像很厉害的东西。随便拿个东西都顶我几个月的生活费，我读书少，又是乡下来的，没见过多少世面，所以我只能默默的看着你发，时不时点个赞。<img src=\"http://img.baidu.com/hi/jx2/j_0002.gif\"/></p><p><br/></p><p><br/></p><p><span style=\"text-decoration: line-through; color: rgb(255, 0, 0);\"><em><strong>上班路上还打醒精神，如今江湖险恶，到处都是坏人。</strong></em></span></p><p><img src=\"http://210.51.17.150:8090/files/lechu/20160528142627980669386.jpg\" title=\"20160528142627980669386.jpg\" alt=\"P60519-154052.jpg\" ></p><p><span style=\"color: rgb(146, 208, 80); text-decoration: none;\">在街上经常会遇到偷偷问你要不要手机的，现在太可怕了，直接明目张胆推销人体器官了，刚才走路无意碰了一女的，还没来得及说对不起，那女的竟然大声问我要不要脸！</span></p>

img标签里边没有宽高，导致返回的 宽高都是－1。

**Comment by shaoyi1991** [comment]
[富文本测试.txt](https://github.com/zzhoujay/RichText/files/287619/default.txt)
我发了 附件文本，你试一下吧。

**Comment by HumorSmith** [comment]
@shaoyi1991 你解决了吗

**Comment by shaoyi1991** [comment]
[富文本测试.txt](https://github.com/zzhoujay/RichText/files/287620/default.txt)
能否收到呢。 @zzhoujay     
主要就是 img标签里边没有 宽高时，没有处理，直接返回－1了。  应该想想如何处理。
不好解决，就只能看看 怎么在富文本里 加上宽和高。

**Comment by zzhoujay** [comment]
我会尽快解决的，请稍等 @shaoyi1991

**Comment by zzhoujay** [comment]
问题已解决，顺带还改了一些其它的地方，整体改动较大，已上传至jcenter，由于改了groupId可能明天审核才能通过，请耐心等待 @shaoyi1991 @HumorSmith 

在新版中可以直接使用自动修复来解决这个问题
```
RichText.from(text).into(textView);
```
或者
```
RichText.from(text).autoFix(true).into(textView);
```

**Comment by zzhoujay** [comment]
审核已经通过了，可以通过`compile 'com.zzhoujay.richtext:richtext:1.1.0'`使用新版了

**Comment by HumorSmith** [comment]
@zzhoujay 谢谢你的帮助。

**Comment by zzhoujay** [comment]
应该的

**Comment by shaoyi1991** [comment]
if (autoFix || holder.isAutoFix()) {
                int width = getRealWidth();
                int height = (int) ((float) resource.getHeight() * width / resource.getWidth());
                urlDrawable.setBounds(0, 0, width, height);
                drawable.setBounds(0, 0, width, height);
            }

    private int getRealWidth() {
        ViewGroup.MarginLayoutParams layoutParams = (ViewGroup.MarginLayoutParams) textView.getLayoutParams();
        return textView.getWidth() - textView.getPaddingRight() - textView.getPaddingLeft() - layoutParams.leftMargin - layoutParams.rightMargin;
    }
按照这个逻辑的话，自动修复 其实就是宽度充满呗。  大图片还好，如果是个表情或者小图片，那也会充满，导致严重失真。

**Comment by zzhoujay** [comment]
你可以取消自动修复，设置自定义修复方法，并根据图片大小判断是否填充
例如这样：
```
        RichText.from(text).autoFix(false).fix(new ImageFixCallback() {
            @Override
            public void onFix(ImageHolder holder, boolean imageReady) {
                if (holder.getWidth() > 200 && holder.getHeight() > 200) {
                    holder.setAutoFix(true);
                }
            }
        }).into(textView);
```

**Comment by zzhoujay** [comment]
你可以取消自动修复，设置自定义修复方法，并根据图片大小判断是否填充
例如这样：
```
        RichText.from(text).autoFix(false).fix(new ImageFixCallback() {
            @Override
            public void onFix(ImageHolder holder, boolean imageReady) {
                if (holder.getWidth() > 200 && holder.getHeight() > 200) {
                    holder.setAutoFix(true);
                }
            }
        }).into(textView);
```
@shaoyi1991
