### ISSUE TITLE
大神，图片可以下载缩略图吗？有下载图片地址的接口吗，阿里云OSS是加图片地址后缀的,原图手机流量有点吃不消呀

### ISSUE THREAD

**Issue by yxyaxng** [zzhoujay/RichText#134]
例如：http://image-demo.oss-cn-hangzhou.aliyuncs.com/example.jpg；
后缀 ?x-oss-process=image/resize,h_100

**Comment by zzhoujay** [comment]
额，那你把源文本图片的src替换成这个不就行了吗？我这个下载图片是根据图片的src来下载的，所以你想下载缩略图，那你就把src改了呗

**Comment by yxyaxng** [comment]
我知道，我只是觉得，如果能把你匹配出来的图片地址，暴露出来接口，我这边直接替换，比较省事

**Comment by zzhoujay** [comment]
在`2.4.5`版本中可以在INIT回调中修改ImageHolder的source了

**Comment by yxyaxng** [comment]
好的，谢谢大神
