### ISSUE TITLE
解析动态图片  图片可能会变黑！

### ISSUE THREAD

**Issue by JamesGZM** [zzhoujay/RichText#135]
ttp://www.51zuoti.com//cgi-bin/mimetex.cgi?K_m  图片地址  原因未知

**Comment by JamesGZM** [comment]
排除原因  得出和缓存有关系 我第一次进入是不会变黑的

**Comment by zzhoujay** [comment]
1. 这是动图吗？看上去并没有动，你指的动图是Gif图的意思吗？
2. 我在我这边测试没出现变黑的问题，你那边变黑是个什么情况？是加载失败的占位图吗？方便给个截图吗？
3. 如果是缓存的关系，那你设置取消缓存试下看还有问题没，`RichText.from(text).cache(CacheType.NONE).into(textView);`

**Comment by JamesGZM** [comment]
@zzhoujay  不是动图 是动态生成的图片  已经解决了 我把缓存设置为none   不是占位图 就是图片背景是白的 它显示为黑色了

**Comment by zzhoujay** [comment]
那好吧
