### ISSUE TITLE
图片点击事件Bug

### ISSUE THREAD

**Issue by PGYH** [zzhoujay/RichText#136]
类似`<img/><img>`这一类两张图片紧挨着的情况，第二张图片的点击事件会出现位置偏差，通常表现为图片的左半侧点击后返回`position`为上一张图的值，而右半侧则正常。

我尝试匹配到每组`<img>`标签在`>`后均添加一个`<br>`标签，这样做可以修复这一Bug，但是感觉这个方法略蠢，希望大大能关注下这个问题，谢谢。

**Comment by PGYH** [comment]
类似`<img/><img>`这一类两张图片紧挨着的情况，第二张图片的点击事件会出现位置偏差，通常表现为图片的左半侧点击后返回`position`为上一张图的值，而右半侧则正常。

我尝试匹配到每组`<img>`标签在`>`后均添加一个`<br>`标签，这样做可以修复这一Bug，但是感觉这个方法略蠢，希望大大能关注下这个问题，谢谢。

**Comment by zzhoujay** [comment]
貌似只能这样解决，因为不加br换行标签的话相当于两个image标签其实是并排的，所以点到左边的时候我这边通过触摸位置得到的是第一个，貌似没啥好办法，抱歉

**Comment by PGYH** [comment]
嗯啊，谢谢您了！
