### ISSUE TITLE
ImageHolder里面的url能自定义吗？

### ISSUE THREAD

**Issue by JamesBondM10** [zzhoujay/RichText#140]
我们的项目中后台返回的url是一个相对路径，需要我们自行添加ip和端口号，请问应该通过什么方法去设置？

**Comment by zzhoujay** [comment]
可以设置下ImageFixCallback，在Init回调中可以修改ImageHolder的Source

```
        RichText.from(text).autoFix(false).fix(new SimpleImageFixCallback() {
            @Override
            public void onInit(ImageHolder holder) {
                String source = holder.getSource();
                holder.setSource(source);
                holder.setAutoFix(true);
            }
        }).into(textView);
```

**Comment by JamesBondM10** [comment]
thank you very much

**Comment by JamesBondM10** [comment]
是不是我没有用最新版本的代码？我这边的ImageHolder中没有setSource方法

**Comment by zzhoujay** [comment]
你试下最新的吧

**Comment by JamesBondM10** [comment]
大神，你好。我的工程在gradle中依赖了你的工程，怎么更新到最新的版本？是直接改版本号吗？

**Comment by jiawei-i** [comment]
dependencies {
       compile 'com.zzhoujay.richtext:richtext:2.4.7'
}

**Comment by yongsheng659** [comment]
大神们求助 为什么不能加载gif图片， 如果特别长的html 会很卡

**Comment by zzhoujay** [comment]
@yongsheng659 特别长卡是指滑动卡还是解析的时候卡？不能加载Gif图？麻烦详细说下

**Comment by zzhoujay** [comment]
@yongsheng659 麻烦新开个issue提

**Comment by JamesBondM10** [comment]
大神，你好。在使用你的工程的时候我发现在以下代码中修改了holder的source，但是图片显示还是异常，请问应该是什么情况：RichText.from(text).autoFix(false).fix(new SimpleImageFixCallback() {
            @Override
            public void onInit(ImageHolder holder) {
                String source = holder.getSource();
                holder.setSource(source);
                holder.setAutoFix(true);
            }
        }).into(textView);
