### ISSUE TITLE
使用DefaultImageGetter， ImageHolder的ScaleType属性就没用了

### ISSUE THREAD

**Issue by ss518926** [zzhoujay/RichText#141]
DefaultImageGetter怎么使ScaleType属性生效

**Comment by zzhoujay** [comment]
DefaultImageGetter目前不支持这个属性

**Comment by ss518926** [comment]
那现在图片居中要怎么实现呢？自己写ImageGetter？

**Comment by zzhoujay** [comment]
你说的居中是指的相对于谁的居中？当然可以自己写ImageGetter来实现

**Comment by ss518926** [comment]
小的图片，屏幕居中
![image](https://cloud.githubusercontent.com/assets/15880922/25081999/5f0b089c-2380-11e7-80b1-d72505cdfce8.png)

**Comment by zzhoujay** [comment]
懂了，过几天我来改下，最近有点忙

**Comment by zzhoujay** [comment]
在`2.5.0`版本中给DefaultImageGetter添加了对ScaleType的支持

你试试看有没有问题

```
RichText
    .from(text)
    .autoFix(false)
    .size(ImageHolder.MATCH_PARENT,ImageHolder.WRAP_CONTENT)
    .scaleType(ImageHolder.ScaleType.FIT_CENTER)
    .into(textView);
```
