### ISSUE TITLE
RichText中的getDrawable执行了两次，第二次执行的时候imageFixCallback为空，导致加载失败。

### ISSUE THREAD

**Issue by JamesBondM10** [zzhoujay/RichText#145]
_大神，你好。我遇到了这么一个问题：由于我们的后台给我们回传的html中只包含了相对路径，需要app自己去处理。于是我在RictText中进行了如下设置：
```
	public static void showHtmlText(final String head, String html, TextView textView){
		RichText.from(html)
				.autoFix(false)
				.fix(new SimpleImageFixCallback() {
					@Override
					public void onInit(ImageHolder holder) {
						String url = holder.getSource();
						Log.i("hahahahahaha oldUrl",url);
						if(!url.startsWith("http") && head != null && !head.equals("")){
							String newUrl = head + url;
							Log.i("hahahahahaha newUrl:",newUrl);
							holder.setSource(newUrl);
							holder.setAutoFix(true);
							holder.setAutoPlay(true);
						}

					}
				})
				.into(textView);
	}
```
我在debug上面的方法的时候遇到了一个问题：我只调用了这个方法一次，然后getDrawable方法执行了两次，第一次执行的时候由于上述方法的设置，imageFixCallback不为空而且autofix为true，所以代码按照我的设置对相对路径进行了修改。但是紧接着代码似乎通过handler又执行了一次getDrawable，第二次执行的时候imageFixCallback变成了null，所以代码就没有按照我的设置而使用了相对路径，导致图片显示失败。大神，请问这个应该怎么改？

**Comment by zzhoujay** [comment]
1. 你说的getDrawable方法是指的ImageGetter的getDrawable方法吗？ImageGetter的getDrawable方法的调用次数是和源文本中图片的个数是一致的。
2. 显示失败是那张图片加载失败还是整个富文本显示失败？
3. onInit方法被调用过几次？
4. 第二次失败的时候onFailure方法有没有被调用？
5. logcat有报错没？

**Comment by JamesBondM10** [comment]
实在是抱歉，我刚刚发现了问题所在。我的同事在同一部分的代码中重新配置了RichText.from().clickable.urlClick().into()，但是他没有设置imageFixCallback，导致ImageGetterWrapper.getDrawable(String source)被调用了两次。
然后回复你的5个问题
1）调用的是ImageGetterWrapper.getDrawable(String source);
2）只是图片加载失败
3）onInit方法只调用了一次
第4、5个我没有找到。可能存在吧。

**Comment by JamesBondM10** [comment]
真是麻烦大神了。
