### ISSUE TITLE
您好 多张图片异步加载显示 滑动的时候 卡顿问题

### ISSUE THREAD

**Issue by yizuochengchi** [zzhoujay/RichText#146]
您好 如题。我用的是Picasso + Target 没办法用fit()对图片进行处理。两张图片紧挨着显示的时候 向上滑动 卡顿。文字滑动正常 有什么建议吗？ 谢谢~

**Comment by zzhoujay** [comment]
只是滑动卡顿的话在TextView外层套个ScrollerView？

**Comment by yizuochengchi** [comment]
谢谢~   ScrollView 嵌套过了 发现是图片过大的原因 3张图 每张3M多 每张压缩成200K 之后就可以了。 不过我遇到一个新的问题 三星手机上 Picasso Target onBitmapFailed  3张图片只显示最后一张。 其他手机正常 不知道怎么回事 还在看。
