### ISSUE TITLE
有时候图片加载不出来？？？也没有显示出占位图

### ISSUE THREAD

**Issue by 523931340** [zzhoujay/RichText#147]

**Comment by zzhoujay** [comment]
你出错的数据和代码发下麻烦

**Comment by clunyes** [comment]
<div class="pictureBox"> 
 <img src="http://static.storeer.com/wlwb/productDetail/3fb933c4-d633-4610-92c9-506e5336b6a1_580x7318.jpeg"> 
</div>

**Comment by zzhoujay** [comment]
我这边一加三 API25 和一个API17的模拟器（内存1.5G）显示都没问题，你的代码是怎样的？

**Comment by clunyes** [comment]
`String text = BizUtil.getContentInBodyTag(goodsDetailBean.getProductDetailPicList());`
        `RichText.fromHtml(text).cache(CacheType.ALL).autoFix(true).error(R.drawable.empty_icon).into(tvGoodsDetail);`
