### ISSUE TITLE
请问能不能调整段间距？文字右端对齐？

### ISSUE THREAD

**Issue by Fish20100903** [zzhoujay/RichText#148]
1、使用richtext显示每个p标签间距都很大，这个怎样解决？添加css样式不起作用
2、文字右端对齐，使用<body style="text-align:justify>也不起作用

**Comment by zzhoujay** [comment]
额，这现状还没办法，因为Html的解析是调用的系统的API来做的，只能等后面自己做个Html解析器才能解决，不过最近要写论文，估计得毕业后才有时间写了
