### ISSUE TITLE
开启硬件加速后，图片宽或者高大于4096，在某些手机上面显示异常

### ISSUE THREAD

**Issue by leexingwang** [zzhoujay/RichText#154]
开启硬件加速后，图片宽或者高大于4096，在某些手机上面显示异常

**Comment by yxyaxng** [comment]
对，我的也出现了

**Comment by zzhoujay** [comment]
只在某些手机上么？显示异常的具体表现如何呢？有没有使用API压缩控制图片的大小呢？出现这个问题时，调整VM大小有没有用呢？

**Comment by zzhoujay** [comment]
可以把TextView的硬件加速关闭来解决这个问题
