### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by tanzhou** [zzhoujay/RichText#157]
请问我想对html中图片链接url进行修改应该怎么弄？

**Comment by tanzhou** [comment]
后台返回的图片链接不正确，这个框架有修改的接口吗？不然图片无法显示

**Comment by zzhoujay** [comment]
调用fix方法设置ImageFixCallback重写onInit方法，在其中使用imageholder.setSource()方法重新指定图片地址，具体可以看看wiki

**Comment by tanzhou** [comment]
好的，谢谢

**Comment by tanzhou** [comment]
RichText.from(mDetails).fix(new ImageFixCallback() {
                    @Override
                    public void onInit(ImageHolder holder) {
                        String url=holder.getSource();
                        String imgUrl=url.replace("http://120.26.43.67:8000", ApiConstants.YNY_BASE_URL);
                        holder.setSource(imgUrl);
                    }
这样可以吗？
