### ISSUE TITLE
assets中图片的路径怎么写？

### ISSUE THREAD

**Issue by linheimx** [zzhoujay/RichText#158]
我有一篇md格式的文档，其中的一些图片在assets中，我要把这些图片显示出来。
尝试了 file:///android_asset/xxx.jpg 这样不可以。

**Comment by linheimx** [comment]
先感谢下作者的辛勤付出 ：）

**Comment by zzhoujay** [comment]
最近忙着毕设没看到，过几天我把这个问题解决下

**Comment by zzhoujay** [comment]
在`2.5.4`版本中加入了assets图片的支持  

使用规则
```
file:///android_asset/xxx.jpg
```
