### ISSUE TITLE
在ListView中不能显示图片

### ISSUE THREAD

**Issue by zhoulujue** [zzhoujay/RichText#16]
尝试了一下如果不是在ListView中，一切正常，但是如果在ListView的cell中不会显示图片。

**Comment by zzhoujay** [comment]
额，我这边在ListView和RecyclerView中测试都没问题，你可以看看我的测试[Demo](https://github.com/zzhoujay/RichText/blob/master/app/src/main/java/zhou/demo/ListViewActivity.java)，看看是不是别的什么原因
