### ISSUE TITLE
项目原本有Glide  okhttp3 和retrofit2， 再用RICHTEXT经常图片不显示

### ISSUE THREAD

**Issue by huyushuai1** [zzhoujay/RichText#163]
请问是有冲突吗 我只依赖了'com.zzhoujay.richtext:richtext:2.5.2'

**Comment by zzhoujay** [comment]
也许是okhttp冲突了，你不用那些的时候会有问题吗？

**Comment by huyushuai1** [comment]
再问下你的okhttp是默认的10秒超时是吗  有提供可以修改时间的方法吗

**Comment by zzhoujay** [comment]
目前没有提供，因为超时是在OkhttpClient构建的时间就要设置好的，不咋好修改，后面看看有啥办法

**Comment by cnccc** [comment]
有okhttp的都会冲突吗？

**Comment by zzhoujay** [comment]
目前`3.0.0`版本已经不再依赖okhttp了
