### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by chaopengTan** [zzhoujay/RichText#168]
![2 emd_f r_6axe7 0z a yx](https://user-images.githubusercontent.com/12883454/27315624-3698ce3a-55ad-11e7-81cf-c62dd565c1f0.png)
![81pi 0uo 9q e0s tkxdh4t](https://user-images.githubusercontent.com/12883454/27315629-39dc7aa6-55ad-11e7-9a04-ffb726848ca7.png)

**Comment by zzhoujay** [comment]
已经加过锁了呀，为什么还会出现这个异常，我这边也重现不出来

**Comment by zzhoujay** [comment]
已在`3.0.0`版本解决
