### ISSUE TITLE
图片显示位置的问题

### ISSUE THREAD

**Issue by SirZhao** [zzhoujay/RichText#17]
为什么每张图片显示都是另起一行呢？
图片和文字能否在同一行显示，当图片高度大于文字高度，文字居中显示，当文字高度大于图片高度，图片居中显示。
这个能实现么？要怎么处理呢？

**Comment by zzhoujay** [comment]
由于HTML解析使用的是Html.fromHtml，而它并没有给我提供图片和文字位置的信息，所以暂时没法实现你想要的功能，如果后续找到了相关的解决方法我会通知你的。

**Comment by SirZhao** [comment]
我看到有一篇博客http://www.cnblogs.com/kimmy/p/5027299.html
这个是说自定义TextView去实现排版问题，我研究半天没弄出来，您能帮忙解决一下么？

**Comment by zzhoujay** [comment]
OK！这问题我会尽力去解决的，不够最近几天忙于期末考试，可能得过几天才能有时间去解决问题

**Comment by SirZhao** [comment]
劳烦能加一下我QQ吗？关于这个RichView我有许多不明白的对方想咨询您，谢谢。676362303

**Comment by jimbocn** [comment]
发现设置.error(R.mipmap.ic_launcher).placeHolder(R.mipmap.ic_launcher)都不能正常显示，需要点击一下图片的位置，这个错误图片才会显示

**Comment by zhizhongchai** [comment]
文字行间距设置不了，如果在xml文件中设置的话，文字和图片的 距离会变得很大

**Comment by zzhoujay** [comment]
@zhizhongchai 确实是这样，原则上行间距应该由Html代码来指定

**Comment by zhizhongchai** [comment]
但是我在html中加代码控制行距，仍旧没有用，可能是Html.fromHtml不支持。

**Comment by zzhoujay** [comment]
@zhizhongchai 恩，Html.fromHtml这个方法确实支持的东西不多，不过我已经在开发原生markdown的支持了，应该过段时间就能加入到其中了，可以在[这里](https://github.com/zzhoujay/Markdown)查看markdown解析器开发的进度
