### ISSUE TITLE
出现内存泄露怎么解决？

### ISSUE THREAD

**Issue by tanzhou** [zzhoujay/RichText#171]
![image](https://user-images.githubusercontent.com/19336837/27722892-d0781fb4-5d9c-11e7-86c1-236dfbb42c9c.png)

**Comment by zzhoujay** [comment]
抱歉啊，回了趟老家github没怎么看，只能8月份去修改各种bug了，如果你找到了解决办法欢迎提交Pull Request

**Comment by zzhoujay** [comment]
这个是由于使用了非静态内部类导致的啊
