### ISSUE TITLE
clear()时AbstractImageLoader.recycle报空指针

### ISSUE THREAD

**Issue by bappleug** [zzhoujay/RichText#176]
除了weakreference判空还要weareference.get判空吧

**Comment by zzhoujay** [comment]
感谢提醒，会在下个版本修复

**Comment by zzhoujay** [comment]
在`2.5.3`版本中已修复

**Comment by nicklxz** [comment]
这邮件怎么一直发我这里，




发自网易邮箱大师
在2017年07月23日 18:05，郑州 写道：

在2.5.3版本中已修复

**Comment by zzhoujay** [comment]
@nicklxz 是不是watch了
