### ISSUE TITLE
ImageWrapperMultiSourceException 异常

### ISSUE THREAD

**Issue by yxyaxng** [zzhoujay/RichText#180]
图片是744*4069
在onSizeReady强制将高设置为3072，出现异常
![image](https://user-images.githubusercontent.com/24906252/28658517-4866cf06-72de-11e7-86f6-fad5fab952f3.png)

**Comment by zzhoujay** [comment]
这个应该是图片解析失败了，不在onSizeReady中设置高度这个异常还会有吗？
安卓设备的版本是多少呢？
