### ISSUE TITLE
请求作者删除demo里相关的测试文字

### ISSUE THREAD

**Issue by GongZiZhang** [zzhoujay/RichText#190]
之前反馈一个bug的时候上传了一段html文字，作者你好像直接把它用在demo里了，那段文字里是有Q群的，现在有些下了demo的人都加那个Q群了，劳请作者把demo里的那段文字去除，或把Q群号码抹去

**Comment by zzhoujay** [comment]
额，这个确实没注意，在下个版本里会把Demo的测试数据都清理一遍

**Comment by zzhoujay** [comment]
已删除
