### ISSUE TITLE
替换RichText里面的正则

### ISSUE THREAD

**Issue by chenwentong0** [zzhoujay/RichText#192]
RichText：
里面的正则
private static Pattern IMAGE_TAG_PATTERN = Pattern.compile("<(img|IMG)(.*?)>");
    private static Pattern IMAGE_WIDTH_PATTERN = Pattern.compile("(width|WIDTH)=\"(.*?)\"");
    private static Pattern IMAGE_HEIGHT_PATTERN = Pattern.compile("(height|HEIGHT)=\"(.*?)\"");
    private static Pattern IMAGE_SRC_PATTERN = Pattern.compile("(src|SRC)=\"(.*?)\"");
能不能添加替换功能？

**Comment by zzhoujay** [comment]
这个你可以在调用RichText前自行处理
