### ISSUE TITLE
markdown语法里面的> 引用标签文字背景色可以变灰色吗?给个思路就好

### ISSUE THREAD

**Issue by ppg408331701** [zzhoujay/RichText#195]
类似下面的**引用标签**

> 参考的代码
> http://www.cnblogs.com/csonezp/p/4956315.html

除了最左边给一条灰色的小线条之外,文本的部分和空白的部分添加浅灰色的背景色
和csdn的markdown编辑器一样.

不奢求大神改,只希望提供一下具体是在那个类里面实现**引用部分**,我自己去研究一下

**Comment by zzhoujay** [comment]
我想到有两种方法

1. 改span的背景颜色，这种做法比较简单，但是如果设置了行间距效果就特别不理想了

2. 使用replacementSpan，做法复杂但自由度较高，不过需要自己处理换行等操作

**Comment by ppg408331701** [comment]
非常感谢
