### ISSUE TITLE
span标签设置的颜色没效果

### ISSUE THREAD

**Issue by drowtram** [zzhoujay/RichText#197]
"<p><span style=\"color:#c0392b\"><strong>这是答案A</strong></span></p>\n"
以上的标签是带有文字颜色的，RichText显示出来的是没有颜色的，期望后期修复

**Comment by zzhoujay** [comment]
后面自定义HTML解析器就可以了，不过最近有点忙，可能要等段时间

**Comment by drowtram** [comment]
感谢，期望后面越来越完善，支持一下
