### ISSUE TITLE
关于图片加载是否可以添加Header

### ISSUE THREAD

**Issue by a843647878** [zzhoujay/RichText#199]
图片加载 是否支持添加Header  因为可能涉及到防盗的问题  需要添加Header   Glide是可以添加的

**Comment by a843647878** [comment]
好吧 找到了  DefaultImageGetter-->131行  添加网络图片  在这里通过Request可以直接addHeader
Request builder = new Request.Builder().url(holder.getSource()).addHeader("****", "****").get().build();

**Comment by zzhoujay** [comment]
因为之前有人提出强制依赖okhttp不太好，所以准备下个版本把okhttp抽离出来，到时候你这个问题可以很好的解决

**Comment by zzhoujay** [comment]
新版本中只需要使用自定义图片加载器即可解决
