### ISSUE TITLE
我试了用Edittext也是可以显示的，但是保存后格式没了

### ISSUE THREAD

**Issue by sendtion** [zzhoujay/RichText#20]
我试了用Edittext也是可以显示的，但是保存后格式没了，都是纯文字，而且图片也没了
请问能否支持html格式文本编辑？编辑后保存为html格式文本？
如果您没有时间，能否给个思路呢？

**Comment by zzhoujay** [comment]
原理上是可以实现的。但是实现比较麻烦，需要在编辑过程中保持所有spanned，如果大家都有这样的需求我可能会在后面加上富文本编辑器的功能，不过最近在做markdown支持的部分，可能得后面点时间才能做这个了，如果比较急的话，我记得github上有一个RichEdit的项目是富文本编辑器，你可以找找看

**Comment by sendtion** [comment]
@zzhoujay 感谢回答，我主要是想做图文混排，github上面有不少可以实现。但是没有一个可以回头来编辑的，但是保存后，可以查看，但是编辑后格式就变了。大神有没有什么好想法？

**Comment by zzhoujay** [comment]
比如删除时可以除了删除字符还得删除字符上的spanned，而且每次操作得保持text的格式，总体上还是挺复杂的很难说清楚

**Comment by sendtion** [comment]
好吧，我再摸索一下。

**Comment by Reteyery** [comment]
@sendtion 有没有好的方式实现图文混排,我现在做得图文混排细节不够好

**Comment by sendtion** [comment]
@Reteyery 可以用ScrollView在里面添加EditText和ImageView来实现
