### ISSUE TITLE
ImageDownloader为空或未设置

### ISSUE THREAD

**Issue by w135153feng73** [zzhoujay/RichText#200]
调用的时候报错，报错信息为：ImageDownloader 为空或未设置
请问这是怎么回事呢？需要做如何设置才能解决该问题呢？

**Comment by zzhoujay** [comment]
你使用的是2.6.0版本么？先不要用那个版本，目前还没正式发布

**Comment by GongZiZhang** [comment]
大概什么时候会有新版？

**Comment by zzhoujay** [comment]
国庆会发布新版的

**Comment by zzhoujay** [comment]
不好意思，推迟到了现在才发布新版本，试试`3.0.0`版本
