### ISSUE TITLE
文本中超链接，添加urlClick跳转不稳定，有时会调起手机自带的浏览器！

### ISSUE THREAD

**Issue by XuPengChen** [zzhoujay/RichText#201]
urlClick(new OnUrlClickListener() {
                    @Override
                    public boolean urlClicked(String url) {
 Intent intent = new Intent(McActivity.this, WebViewActivity.class);
                        intent.putExtra("webUrl", url);
                        startActivity(intent);
                        return true;
                    }
                })

**Comment by kingvan** [comment]
我发现一个规律,第一次点没问题，第二次就不走定义事件了

**Comment by shouzhong** [comment]
把长点击事件也设置了就不会出现那个情况了

**Comment by kingvan** [comment]
@shouzhong  我把长点击事件也设置了 ，2.5.4版本上还是不可以啊，3.0.0一用就莫名其妙的崩溃

**Comment by qiufeng1230** [comment]
大神，赶快解决一下这个问题呀

**Comment by zzhoujay** [comment]
试试3.0.4版本
