### ISSUE TITLE
关于缓存策略的疑问

### ISSUE THREAD

**Issue by nichbar** [zzhoujay/RichText#203]
[翻看代码](https://github.com/zzhoujay/RichText/blob/26b3dee2e42a734c9016ab1437e652fd68ea19fa/richtext/src/main/java/com/zzhoujay/richtext/ig/BitmapPool.java#L30)发现图片只有在内存缓存里 evicted 或 removed 的时候才会缓存至磁盘。

这样的策略是否不太合理呢？倘若 LruCache 的值一直达不到上限或者没有手动移除内存缓存的话（都手动[移除缓存](https://github.com/zzhoujay/RichText/blob/e3caa516dbaba486ac3387f5f1ef10428008a789/richtext/src/main/java/com/zzhoujay/richtext/RichText.java#L70)了才把内存缓存缓存到磁盘 =。=），那么
DiskLruCache 将不会起效，造成了一直没有 DiskLruCache 可用的情况。

个人觉得正常的缓存策略应该是内存缓存和磁盘缓存同时进行，而不是内存不要了才给磁盘。

如果上面说的有错误，敬请原谅。 Have a nice day  : ）

**Comment by zzhoujay** [comment]
缓存策略确定有点问题，可能会导致程序异常终止的时候内存里的数据无法持久化下来，国庆会重新设计一下缓存策略，感谢提醒

**Comment by zzhoujay** [comment]
缓存策略已在`3.0.0`版本中修改
