### ISSUE TITLE
设置缓存为ALL，缓存的图片会变绿

### ISSUE THREAD

**Issue by FeiMAndroid** [zzhoujay/RichText#206]
设置缓存为ALL，过段时间再打开，显示的图片变绿了，这是什么原因？
`RichText.fromHtml(article.getContent())
                            .cache(CacheType.ALL)
                            .into(activity_article_content_tv);`

**Comment by yaochangliang159** [comment]
同问，我是viewpager+fragment,然后每个fragment 都是有个recyclerview列表。，每个列表的item都是富文本，我滑过去几页，再划回来，之前显示的好好的富文本，就变成了一个正方形的绿色的小块，

**Comment by qianyue0317** [comment]
同问

**Comment by zzhoujay** [comment]
@yaochangliang159 @qianyue0317 可以发一张效果图么？初步判断应该是图片被回收了

**Comment by FeiMAndroid** [comment]
@zzhoujay 
![image](https://user-images.githubusercontent.com/12498999/32357560-c9c244d0-c078-11e7-8f8e-6af4372c2a66.png)
![image](https://user-images.githubusercontent.com/12498999/32357563-d4c366ac-c078-11e7-8c66-9d48530cf443.png)
第一张是正常的

**Comment by yaochangliang159** [comment]
如图，第一张是正常的情况，第二张是我刷新的viewpager的adapter之后，就变成了小绿块，哦对了，，这些富文本里面是有BASE64的图片的。。。然后列表控件我用的recyclerview
![qq 20171129083824](https://user-images.githubusercontent.com/13497352/33351892-f13f26d2-d4e0-11e7-9bbd-635995014020.png)
![qq 20171129083830](https://user-images.githubusercontent.com/13497352/33351898-f5cf583e-d4e0-11e7-928d-a5d26bf921c1.png)

**Comment by zzhoujay** [comment]
@yaochangliang159 你这问题我这边重现过了，在定位中，后面解决了会通知你

**Comment by zzhoujay** [comment]
试下`3.0.3`版本，这个问题应该已经修复了
