### ISSUE TITLE
DefaultImageGetter会出现ConcurrentModificationException异常

### ISSUE THREAD

**Issue by wxliao** [zzhoujay/RichText#211]
看源码，虽然作者用了lock，但是由于这个DefualtImageGetter的实例是在RichTextConfig里new出来的，而在ListView或者RecyclerView里TextView会重用，如果按demo里边的写法，lock貌似不太好使。

请问有没有什么好的解决办法？这个DefualtImageGetter是不是可以在Adapter里使用同一个实例。

**Comment by zzhoujay** [comment]
这个最近在优化，由于临时出差了，进度暂停了两周，下个版本会尽量修复这个问题的

**Comment by zzhoujay** [comment]
这个问题在`3.0.0`版本里应该已经解决了，目前全局采用一个ImageGetter，应该不会有这个问题了
