### ISSUE TITLE
Set TextView style

### ISSUE THREAD

**Issue by iferrant** [zzhoujay/RichText#212]
Is there any possibility to create a text style ? When you set the color of the TextView, you can't change the header's color. As you can see in the example, I change the text color depending on the background color, but I could not find the way to change the header color and they are in the same TextView.

### Example:
Text color: white
![captura de pantalla 2017-11-12 a las 23 33 26](https://user-images.githubusercontent.com/579796/32704242-37cf9da2-c802-11e7-8ab5-7f0186719218.png)

Text color: black
![captura de pantalla 2017-11-12 a las 23 33 00](https://user-images.githubusercontent.com/579796/32704243-37eb27fc-c802-11e7-94c7-b3f2263e294f.png)

_Thank you for your work_

**Comment by zzhoujay** [comment]
Your source text is markdwon format? The current markdown parser on the header is hard-coded way, so it appeared this situation. We'll consider adding more custom styles later, but I've been busy lately and the RichText project still has work to do, so I might move on to markdown later.

_Thank you for your support._

**Comment by iferrant** [comment]
> We'll consider adding more custom styles later

Glad to hear that ! I look forward for the new options.
