### ISSUE TITLE
不能显示长图

### ISSUE THREAD

**Issue by yuiopt** [zzhoujay/RichText#213]

**Comment by zzhoujay** [comment]
麻烦详细描述下，发下出问题的源文本啥的，方便我定位问题

**Comment by yuiopt** [comment]
图片高度有1万多像素，富文本如下

<style>
    .vm {
        width: 50px;
        height: 50px;
    }
</style>
<div class="text">第一课的文字部分.
    <br /> 第001讲丨战俘营里的经济组织
    <br />
</div>
<a href="http://bbs.stoneread.com/data/attachment/forum/201710/31/203915bjwzg0i7jvw1e1w7.mp3&filename=第001讲丨战俘营里的经济组织.mp3&isaudio=1&aid=134"
    class="attach clickplay" rel="1" ext="mp3" isaudio="1" style="color:#000;text-decoration:none;">
    <div style="width:100%;height:50px;background-color:#FBFBFB;border:1px solid #F8F8F8;">
        <div style="float:left;width:50px;height:50px;">
            <img src="http://bbs.stoneread.com/static/image/filetype/av.gif" border="0" class="vm" alt="" />
        </div>
        <div style="float:left;width:80%;height:50px;margin-left:10px;">
            <div style="width:100%;height:30px;font-size:16px;overflow:hidden;white-space: nowrap;text-overflow: ellipsis;">第001讲丨战俘营里的经济组织.mp3</div>
            <div style="width:100px;height:20px;line-height:20px;font-size:10px;font-color:#ccc;display:inline-block;">6.47 MB</div>
        </div>
        <div style="clear:both;"></div>
    </div>
</a>
<div class="text">
    <br />
    <br />
    <br />
    <div class="img">
        <img src="http://bbs.stoneread.com/data/attachment/forum/201710/31/202033r09da9n8cauc58pc.jpg" attach="1557798" />
    </div>
    <br />
    <br />
    <br />
    <br />
</div>

**Comment by molilian** [comment]
我也遇到了这个问题 ，麻烦帮忙看一下是什么原因
  <img src="https://img20.360buyimg.com/vc/jfs/t1/3529/29/3729/3258912/5b9a171dEe1a620b3/3510c2581bc37064.jpg"/>

[https://img20.360buyimg.com/vc/jfs/t1/3529/29/3729/3258912/5b9a171dEe1a620b3/3510c2581bc37064.jpg](url)
