### ISSUE TITLE
网络图片不能显示

### ISSUE THREAD

**Issue by shcc** [zzhoujay/RichText#215]
W/System.err: java.io.IOException: BufferedInputStream is closed
W/System.err:     at java.io.BufferedInputStream.streamClosed(BufferedInputStream.java:125)
W/System.err:     at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
W/System.err:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/System.err:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
W/System.err:     at com.zzhoujay.richtext.ig.SourceDecode$3.decodeSize(SourceDecode.java:85)
W/System.err:     at com.zzhoujay.richtext.ig.SourceDecode$3.decodeSize(SourceDecode.java:68)
W/System.err:     at com.zzhoujay.richtext.ig.AbstractImageLoader$override.getDimensions(AbstractImageLoader.java:209)
W/System.err:     at com.zzhoujay.richtext.ig.AbstractImageLoader$override.doLoadImage(AbstractImageLoader.java:236)
W/System.err:     at com.zzhoujay.richtext.ig.AbstractImageLoader$override.access$dispatch(AbstractImageLoader.java)
W/System.err:     at com.zzhoujay.richtext.ig.AbstractImageLoader.doLoadImage(AbstractImageLoader.java:0)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.tools.fd.runtime.AndroidInstantRuntime.invokeProtectedMethod(AndroidInstantRuntime.java:143)
W/System.err:     at com.zzhoujay.richtext.ig.CallbackImageLoader$override.onImageDownloadFinish(CallbackImageLoader.java:38)
W/System.err:     at com.zzhoujay.richtext.ig.CallbackImageLoader$override.access$dispatch(CallbackImageLoader.java)
W/System.err:     at com.zzhoujay.richtext.ig.CallbackImageLoader.onImageDownloadFinish(CallbackImageLoader.java:0)
W/System.err:     at com.zzhoujay.richtext.ig.ImageDownloaderManager$Task$override.run(ImageDownloaderManager.java:151)
W/System.err:     at com.zzhoujay.richtext.ig.ImageDownloaderManager$Task$override.access$dispatch(ImageDownloaderManager.java)
W/System.err:     at com.zzhoujay.richtext.ig.ImageDownloaderManager$Task.run(ImageDownloaderManager.java:0)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
D/skia: ---- read threw an exception
D/skia: --- SkImageDecoder::Factory returned null

使用的是DefaultImageDownloader，尝试用okhttp那个也是报一样的错，
图片是可以访问的http://f.hiphotos.baidu.com/image/pic/item/cb8065380cd791234275326baf345982b2b7801c.jpg
download状态是200，

源html代码中只有一张图片， 多张图片也是不能显示的。

调试机可以上网

**Comment by shcc** [comment]
经过调试，后来才发现
即使是设置了Cache.None，还是要经过
InputStream inputStream = BitmapPool.getPool().readBitmapFromTemp(key);
这个步骤，
因此，第一次使用之前，一定要调用
RichText.initCacheDir();
方法才可以显示图片。

**Comment by zzhoujay** [comment]
是的，因为如果直接从网络流decode很有可能由于连接关闭而失败，所以现在是先写入缓存然后再decode，所以必须要设置缓存目录
