### ISSUE TITLE
listview中滑动，上滑无问题，下滑会导致跳动

### ISSUE THREAD

**Issue by kingvan** [zzhoujay/RichText#216]
1.listview 一般是在有图片或者有URL的时候，会小幅度跳动，
2.recycle view中会有可能在，下滑时自动跳到顶部，我换成listview就没有跳到顶部的问题了

**Comment by zzhoujay** [comment]
这个问题是recyclerView自己的缓存机制导致的，目前还没有找到比较好的解决方案
