### ISSUE TITLE
引入编译出错

### ISSUE THREAD

**Issue by PengornisHe** [zzhoujay/RichText#22]
![image](https://cloud.githubusercontent.com/assets/12790677/16370858/7d5fc136-3c75-11e6-80eb-3a8463c76475.png)
![image](https://cloud.githubusercontent.com/assets/12790677/16370865/869006e4-3c75-11e6-8287-4b870e5f9ec1.png)
![image](https://cloud.githubusercontent.com/assets/12790677/16370869/8faf6da0-3c75-11e6-8ce6-042f7d320571.png)
不知道啥原因

**Comment by zzhoujay** [comment]
这个应该不是我的库的原因，这个库没有定义任何style，你逐各排查下，看看是不是其它的原因

**Comment by PengornisHe** [comment]
第一个错误貌似是样式重复，处理掉了；第二错误貌似是版本兼容问题compile 'com.android.support:support-v4:22.2.1'，不好处理呀。

**Comment by zzhoujay** [comment]
貌似是我的库用的support库版本比你的项目高，你可以先改为最新版，或者等晚上我发一个新版本去掉support库依赖。
