### ISSUE TITLE
最新的和最老的  无限崩ConcurrentModificationException

### ISSUE THREAD

**Issue by danniu1314** [zzhoujay/RichText#222]

**Comment by zzhoujay** [comment]
3.0.3版本必现吗？能给下触发问题的源文本，和出错的异常信息吗？

**Comment by boxpro** [comment]
修改了DefaultImageGetter.java 中的checkTarget 源码，解决了这个问题    
private void checkTarget(TextView textView) {
        synchronized (DefaultImageGetter.class) {
            //noinspection unchecked
            HashSet<Cancelable> cs = (HashSet<Cancelable>) textView.getTag(TASK_TAG);
            if (cs != null) {
                if (cs == tasks) {
                    return;
                }
                _HashSet<Cancelable> _cs = new HashSet<Cancelable>(cs);
                Iterator<Cancelable> it = _cs.iterator();
                while (it.hasNext()) {
                    Cancelable c = it.next();
                    c.cancel();
                }_
                _cs.clear();
                cs.clear();
            }
            textView.setTag(TASK_TAG, tasks);
        }
    }

**Comment by zzhoujay** [comment]
感谢，下个版本会合入这个修改

**Comment by zzhoujay** [comment]
已在3.0.4版本合入了修改

**Comment by boxpro** [comment]
举手之劳，不客气不客气。
