### ISSUE TITLE
图片路径显示问题

### ISSUE THREAD

**Issue by AnRuoXi** [zzhoujay/RichText#227]
一般从网站上获取的链接都是相对路径，RichText好像不支持相对路径的设置，导致图片不能显示。

**Comment by zzhoujay** [comment]
不支持相对路径，因为我也不知道应该是相对于哪里的路径，可以设置ImageFixCallback在onInit回调里重新给imageHolder设置source

**Comment by AnJiuZhe** [comment]
@zzhoujay 谢谢，希望作者有时间能把recyclerview支持gif显示的功能完善，这个开源库非常好用，加油！
