### ISSUE TITLE
html img base64怎么支持

### ISSUE THREAD

**Issue by shingohu** [zzhoujay/RichText#229]
html中img标签采用的是Data URI scheme base64的方式加载的图片,如何处理兼容

**Comment by zzhoujay** [comment]
支持这种格式的
```
^data:image/\w+?;.*?base64,(.*)
```
若是不兼容，可以设置ImageFixCallback在onInit方法里重新给ImageHolder设置Source

**Comment by shingohu** [comment]
@zzhoujay 看了下源码确实有base64的处理  但是发现个问题 
Base64ImageLoader 中
 byte[] src = Base64.decode(holder.getSource());

holder.getSource 应该要处理下吧 
这个数据是 data:image....bas64,xxx   应该是要取base64后面那部分的数据加载吧
