### ISSUE TITLE
你好为什么设置设置加载失败的错误图和占位图不能正常显示呢？

### ISSUE THREAD

**Issue by jimbocn** [zzhoujay/RichText#23]
RichText.from(IMAGE1).autoFix(false).error(R.mipmap.ic_launcher)设置好后并不能显示吗，而是点击一下图片所在位置才能正常显示

**Comment by zzhoujay** [comment]
已经找到原因了，error和placeholder图片加载后没及时刷新textview，非常感谢你发现了这个问题，我晚上修复发布新版本后会马上通知你的

**Comment by jimbocn** [comment]
好的，感谢弄出这么好的控件，另外请教下如果想点击图片重新加载，是需要这样重新加载吗 mRichText.imageClick(new OnImageClickListener() {
            @Override
            public void imageClicked(List<String> imageUrls, int position) {
                mRichText.into(textView);
            }
        });

**Comment by zzhoujay** [comment]
不需要重新用richtext加载，只需要重新设置一下textview就行了：textView.setText(textView.getText())

**Comment by jimbocn** [comment]
恩 谢谢，确实可以

**Comment by zzhoujay** [comment]
好了，已经在1.1.5版本修复了这个问题
