### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by 1119093254** [zzhoujay/RichText#232]
换了最新版本的    图片不显示   图片点击  事件地址是对的，这可能是什么原因导致的？

**Comment by zzhoujay** [comment]
麻烦详细描述下：

1. 使用的是markdown还是Html
2. 新版指的是哪个版本
3. GIF图还是静态图
4. 是在ListView或RecyclerView中吗
5. 使用Demo里面的图片src可以显示吗
