### ISSUE TITLE
 要设置header如何实现

### ISSUE THREAD

**Issue by HeavenWen** [zzhoujay/RichText#233]
要设置header如何实现

**Comment by zzhoujay** [comment]
什么意思？设置什么header？麻烦详细描述下

**Comment by HeavenWen** [comment]
网站图片加了防盗链，所以显示图片时，需要设置Referer，不知如果设置

**Comment by zzhoujay** [comment]
设置自定义ImageDownloader，自己处理图片下载的逻辑就可以了
