### ISSUE TITLE
AsyncTask

### ISSUE THREAD

**Issue by shichunlei** [zzhoujay/RichText#234]
android.view.ViewRootImpl$CalledFromWrongThreadException
Only the original thread that created a view hierarchy can touch its views.

java.lang.RuntimeException:An error occured while executing doInBackground()
--
 android.os.AsyncTask$3.done(AsyncTask.java:304)
 ......
 Caused by:
 android.view.ViewRootImpl$CalledFromWrongThreadException:Only the original thread that created a view hierarchy can touch its views.
 android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6403)
 android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:931)
 android.view.ViewGroup.invalidateChild(ViewGroup.java:4690)
 android.view.View.invalidateInternal(View.java:11807)
 android.view.View.invalidate(View.java:11771)
 android.view.View.invalidate(View.java:11755)
 android.widget.TextView.checkForRelayout(TextView.java:6881)
 android.widget.TextView.onRtlPropertiesChanged(TextView.java:8989)
 android.view.View.resolvePadding(View.java:13362)
 android.view.View.getPaddingLeft(View.java:16611)
 com.zzhoujay.richtext.c$a$1.a(RichTextConfig.java:477)
 com.zzhoujay.richtext.ImageHolder.<init>(ImageHolder.java:141)
 com.zzhoujay.richtext.b.e(RichText.java:283)
 com.zzhoujay.richtext.b.d(RichText.java:230)
 com.zzhoujay.richtext.b.a(RichText.java:37)
 com.zzhoujay.richtext.b$a.a(RichText.java:183)
 com.zzhoujay.richtext.b$a.doInBackground(RichText.java:167)
 android.os.AsyncTask$2.call(AsyncTask.java:292)
 java.util.concurrent.FutureTask.run(FutureTask.java:237)
 android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 java.lang.Thread.run(Thread.java:818)

**Comment by zzhoujay** [comment]
试试3.0.5版本，因为getPadding有可能出发重绘，这个版本把这个操作放到主线程
