### ISSUE TITLE
为什么新版本图片不显示了

### ISSUE THREAD

**Issue by lidldesigner** [zzhoujay/RichText#236]
如题

**Comment by lidldesigner** [comment]
多了两个转义符号就有问题了

**Comment by zzhoujay** [comment]
麻烦详细描述下：
1. 使用的是markdown还是Html
2. 新版指的是哪个版本
3. GIF图还是静态图
4. 是在ListView或RecyclerView中吗
5. 使用Demo里面的图片src可以显示吗

**Comment by shichunlei** [comment]
@lidldesigner 你看一下是不是在使用之前没有加上 RichText.initCacheDir(this); 这一句，我也遇到了你说的问题，加上这句之后图片可以显示了，希望能帮到你。

我用的3.0.5版本

**Comment by yjlswykj** [comment]
html 用gif的例子也不显示，h标签也识别不了 版本3.0.5 ，不在ListView或RecyclerView

**Comment by yjlswykj** [comment]
是我数据的问题 但是好像有序列表不能识别
