### ISSUE TITLE
java.lang.ClassCastException: android.view.ViewGroup$LayoutParams cannot be cast to android.view.ViewGroup$MarginLayoutParams

### ISSUE THREAD

**Issue by yinhangfeng** [zzhoujay/RichText#24]
java.lang.ClassCastException: android.view.ViewGroup$LayoutParams cannot be cast to android.view.ViewGroup$MarginLayoutParams
at com.zzhoujay.richtext.RichText.getRealWidth(RichText.java:369)

**Comment by zzhoujay** [comment]
This issue has been fixed in the 1.1.6 version.
