### ISSUE TITLE
文字边距大小如何设置?

### ISSUE THREAD

**Issue by Reteyery** [zzhoujay/RichText#25]

**Comment by zzhoujay** [comment]
额，边距大小原则上是HTML代码里设置的，不过TextView中应该也是可以做相应的设置的

**Comment by Reteyery** [comment]
textview可以设置整体的样式,但是文字和图片之间的边距可以调么...

**Comment by zzhoujay** [comment]
额，现在还不行呢，现在图片和文字不能在同一排，后面可能会想办法解决，因为最近忙于开发markdown功能
