### ISSUE TITLE
不支持img真实地址解析

### ISSUE THREAD

**Issue by wapchief** [zzhoujay/RichText#250]
html解析器解析img地址的时候http协议不能自动转换https协议。

可能出现的情况是：后台返回的html文本 imgurl是http协议类型，但是复制到浏览器打开其实是https类型。这样RichText 就无法识别，图片的位置是灰色的占位

目前的解决方案是让后台把返还带img标签中的地址，修改成统一的https。

否则RichText 不能识别.

**Comment by zzhoujay** [comment]
可以设置ImageFixCallback在init回调中自己替换source

或者设置自定义ImageDownloader自己处理下载逻辑
