### ISSUE TITLE
无法使用gradle添加依赖

### ISSUE THREAD

**Issue by ShuttleSpace** [zzhoujay/RichText#258]
升级了Android studio 3.1 后报错：
Unable to resolve dependency for ':examlib@debug/compileClasspath': Could not resolve com.zzhoujay:html:latest-version.

按照网上的方法，在buildTypes 中添加了 debug{matchingFallbacks = ['release']}也无效
请问怎么解决？？？

**Comment by zzhoujay** [comment]
latest-version 指的是最新的版本号，使用的时候需要更换成最新的版本号，最新版本号在readme标题的右边有
