### ISSUE TITLE
android stdudio 3.0引入报错

### ISSUE THREAD

**Issue by fengyongge** [zzhoujay/RichText#259]
android stdudio 3.0引入报错

**Comment by zzhoujay** [comment]
麻烦把报错信息发一下，谢谢

**Comment by zimengfang** [comment]
Failed to resolve: com.zzhoujay:html:latest-version

**Comment by zzhoujay** [comment]
额，latest-version的意思的替换成最新版本号，最新的版本号在ReadMe的标题上有
