### ISSUE TITLE
图片没有显示全屏问题

### ISSUE THREAD

**Issue by TenXu** [zzhoujay/RichText#268]
楼主，自从您上次更新之后这个框架更好用了，但是现在后台又给了一段神奇的富文本，导致了图片没有办法全屏，但有些地方的富文本却没有问题；以下给您一段有问题的富文本，一起研究研究到底是哪里出的问题导致图片没有显示全屏。
```
<p style="text-align:center;line-height:150%">打开下面按钮，获取课程大纲</p><p style="line-height: 150%; text-align: center;">▼</p><p style="line-height: 150%;"><img src="http://img1.huazhen2008.net/images/common/201805/24/rqxfryvrobgl5bplpwsnopj0bdv3kryc.jpg" title="http://img1.huazhen2008.net/images/common/201805/24/rqxfryvrobgl5bplpwsnopj0bdv3kryc.jpg" alt="xq_02.jpg"/><br/></p><p><img src="http://img1.huazhen2008.net/images/common/201805/24/fvggstg1ineh2p8f3edjaa4ftao2pfrn.jpg" title="http://img1.huazhen2008.net/images/common/201805/24/fvggstg1ineh2p8f3edjaa4ftao2pfrn.jpg" alt="xq_03.jpg"/></p>
```

**Comment by TenXu** [comment]
因怕图片地址内容有改动，先把图片下载下来给您
![rqxfryvrobgl5bplpwsnopj0bdv3kryc](https://user-images.githubusercontent.com/12495409/40896453-97e66146-67e7-11e8-852d-5af595daac16.jpg)
![fvggstg1ineh2p8f3edjaa4ftao2pfrn](https://user-images.githubusercontent.com/12495409/40896454-9b73aa58-67e7-11e8-9521-0c9e5cee34d1.jpg)

**Comment by zzhoujay** [comment]
1. 全屏的意思是指以横向拉升至填充吗
2. 这段测试文本中的图片都有问题吗
3. 方便贴一下richtext使用的代码吗

**Comment by TenXu** [comment]
打扰了，问题貌似算是解决了，我把TextView的宽度属性改成了`match_parent`，原本是wrap_content，嗯。。。。算是粗心导致的吧，不过还是有点疑问，为什么在`wrap_content`情况下，有的可以拉伸填充，有的不可以

**Comment by zzhoujay** [comment]
如果图片填充最宽只能到textview的宽度，wrap_content的话textview的宽度是有text的宽度决定的，所以如果有的文本不够长的话就会出现了

**Comment by TenXu** [comment]
嗯嗯，理解，是这么个道理
