### ISSUE TITLE
gradle 编译不过去啊 请问你的库放在哪里的

### ISSUE THREAD

**Issue by lrain-lv** [zzhoujay/RichText#269]

**Comment by lrain-lv** [comment]
Error:(98, 13) Failed to resolve: com.zzhoujay.richtext:richtext:3.0.7

**Comment by lrain-lv** [comment]
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.google.com' }
        maven { url "https://jitpack.io" }
    }
}

**Comment by zzhoujay** [comment]
在jcenter中确实是有的，可以访问链接查看  

https://dl.bintray.com/zzhoujay/maven/com/zzhoujay/richtext/richtext/3.0.7/

**Comment by lrain-lv** [comment]
请问这是什么问题:
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_hiapkDebugApkCopy'.
   > Could not resolve com.zzhoujay.richtext:richtext:3.0.7.
     Required by:
         project :app
      > Could not resolve com.zzhoujay.richtext:richtext:3.0.7.
         > Could not get resource 'https://jcenter.bintray.com/com/zzhoujay/richtext/richtext/3.0.7/richtext-3.0.7.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/zzhoujay/richtext/richtext/3.0.7/richtext-3.0.7.pom'.
               > android-mirror.bugly.qq.com
      > Could not resolve com.zzhoujay.richtext:richtext:3.0.7.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/zzhoujay/richtext/richtext/3.0.7/richtext-3.0.7.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/zzhoujay/richtext/richtext/3.0.7/richtext-3.0.7.pom'.
               > android-mirror.bugly.qq.com
      > Could not resolve com.zzhoujay.richtext:richtext:3.0.7.
         > Could not get resource 'https://jitpack.io/com/zzhoujay/richtext/richtext/3.0.7/richtext-3.0.7.pom'.
            > Could not GET 'https://jitpack.io/com/zzhoujay/richtext/richtext/3.0.7/richtext-3.0.7.pom'.
               > android-mirror.bugly.qq.com
      > Could not resolve com.zzhoujay.richtext:richtext:3.0.7.
         > Could not get resource 'https://dl.bintray.com/zzhoujay/maven/com/zzhoujay/richtext/richtext/3.0.7/richtext-3.0.7.pom'.
            > Could not GET 'https://dl.bintray.com/zzhoujay/maven/com/zzhoujay/richtext/richtext/3.0.7/richtext-3.0.7.pom'.
               > android-mirror.bugly.qq.com

**Comment by zzhoujay** [comment]
有没有试过其他jcenter仓库的库，是不是网络问题

**Comment by lrain-lv** [comment]
链接点开都是可以直接下载的，但是就是编译不过去，不知道是不是最后的qq镜像的问题
