### ISSUE TITLE
"#"符号不能解析

### ISSUE THREAD

**Issue by HumorSmith** [zzhoujay/RichText#27]
####你会原样显示出来

**Comment by zzhoujay** [comment]
其实并不是不能解析\#号，而是\#后面需要有至少一个空格才行，也就是`# hello`这种，之所以这样设计是因为个人的习惯吧，刚试了下Github确实也认`#hello`这种，我会尽快把这个修改下的

**Comment by zzhoujay** [comment]
在`2.0.2`版本中把这个限制去掉了

**Comment by HumorSmith** [comment]
好的，已经知悉.你试过图片标签吗 ![]()我试过，好像不太好用

**Comment by zzhoujay** [comment]
@HumorSmith 额，`[]()`是链接，`![]()`才是图片

**Comment by HumorSmith** [comment]
我知道...你试试   ``` ![]() ```

**Comment by zzhoujay** [comment]
我当然是测试过的，你把你出问题的源文本贴一下

**Comment by zzhoujay** [comment]
@HumorSmith 希望能够提供一些出问题的源文本，方便定位问题
