### ISSUE TITLE
能加上支持webp动态图吗?

### ISSUE THREAD

**Issue by renyanxu2000** [zzhoujay/RichText#28]

**Comment by zzhoujay** [comment]
测试了下webp格式的图片是支持的，Gif动态图也是支持的，不清楚你说的webp动态图是什么

**Comment by renyanxu2000** [comment]
http://www.gstatic.com/webp/animated/1.webp
用chrome浏览器访问这个链接。

**Comment by zzhoujay** [comment]
经过一些测试发现Glide并不支持webp的动态图，并且webp图片也只支持高版本的安卓系统，由于RichText图片加载是用Glide来做的，所以也是不支持webp动态图
