### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by csh159** [zzhoujay/RichText#3]
首次打开前面几张图片不显示，不知道为什么，下面3张会显示，好像我用AsyncTask 重写了请求的就都显示，这是为什么？

**Comment by zzhoujay** [comment]
是由于Picasso对Target没有持有强引用造成的，图片一多其他的就会被释放掉，只要我们自己给对他持有一个强引用就行了，具体查看 http://stackoverflow.com/questions/24180805/onbitmaploaded-of-target-object-not-called-on-first-load，今天会修复这个问题
