### ISSUE TITLE
图片加载

### ISSUE THREAD

**Issue by houlucky** [zzhoujay/RichText#31]
请问此富文本text加载网络图片是用的什么呢？ 可以自己调用glide吗？  我试了一下加载不出这种[img  src]格式的图片

**Comment by zzhoujay** [comment]
是用Glide加载的图片，现在暂时还不能自己去调用Glide去加载图片，不过后面可以尝试开放一个这样的接口，话说[img src]是啥格式？现在富文本只支持Markdown和HTML，所以相应的图片的格式也只支持markdown风格的`![]()`和`![][]`和HTML风格的`<img src="...">`
