### ISSUE TITLE
图文长按点击和长按复制文字冲突

### ISSUE THREAD

**Issue by rogerou** [zzhoujay/RichText#33]
长按图片回调和长按复制文字会冲突

**Comment by zzhoujay** [comment]
这个应该不是图片长按回调引起的冲突，TextView使用的文本源是Spanned后长按复制默认就是不启用的，可以在xml的TextView添加属性：`android:textIsSelectable="true"`开启，亲测可用

**Comment by rogerou** [comment]
@zzhoujay 我就是开启了这个，冲突不是说不能使用，而开了这个，长按图片  也会复制和保存图片

**Comment by zzhoujay** [comment]
懂了，因为我的长按是通过设置的自定义MovementMethod实现的，而setTextIsSelectable会把TextView的MovementMethod设置为ArrowKeyMovementMethod，所以长按事件也没了，而且在测试过程中感觉ArrowKeyMovementMethod对Span的处理好像有问题，在长按弹出复制悬浮框后直接点框外很大几率crash．我尝试下把LinkMovementMethod和ArrowKeyMovementMethod整合下，ｏｋ了再通知你

**Comment by zzhoujay** [comment]
研究了下TextView源码，发现只要`setTextIsSelectable(true)`后，TextView的touch事件就不可避免的被分发到SelectionController（负责控制选择文字的游标和pop menu的）中去，而且SelectionController中没对所复制的文本做任何判断也就是说我们没法干预这个过程，所以只要长按悬浮窗的出现我们貌似是无法控制的，除非`setTextIsSelectable(false)`直接禁用

**Comment by rogerou** [comment]
@zzhoujay 但是禁用了就无法长按复制了阿

**Comment by zzhoujay** [comment]
@rogerou 对呀，现在很尴尬，我现在没想到什么好的解决方案，感觉Android设计时就没考虑过这种情况，你有没有什么好的解决方案分享下吧😂
