### ISSUE TITLE
图片的点击问题

### ISSUE THREAD

**Issue by HeavenWen** [zzhoujay/RichText#35]
发现图片的点击事件有几个问题：
1.GifActivity中点击第一张图，图片上方会出现大约5像素的背景条
2.如果autoFix(false)，textview的宽也设置wrap_content，要显示的内容中有两张图片垂直排列，第二张图片的宽度比第一张图片小，这时候第二张图的点击宽度是第一张图的宽度，也就是点击第二张图右边小于第一张图片宽度的空白的地方也会响应点击事件
3.点击图片手指移动到其他地方再松开，也会响应点击事件，跟一般OnClick事件不一样
望解决！！！

**Comment by zzhoujay** [comment]
* GifActivity中出现的图片上边类似margin的东西应该是Html.fromHtml生成样式的问题,这个我也没啥办法控制.
* 后面关于图片空白部分也可以点击的问题已经修复了,请使用`2.0.9`版本

感谢指出这些问题
