### ISSUE TITLE
RecyclerView中显示gif时有严重的图片错位问题

### ISSUE THREAD

**Issue by denghui1010** [zzhoujay/RichText#36]
RecyclerView中显示gif时有严重的图片错位问题

**Comment by zzhoujay** [comment]
是怎样的错位情况?我这边测试没有出现错位,麻烦详细描述下

**Comment by denghui1010** [comment]
把RecyclerViewActivity中的数据换成:
        "<h3>Test1</h3><img src=\"http://www.aikf.com/ask/resources/images/facialExpression/qq/1.gif\" />",
        "<h3>Test2</h3><img src=\"http://www.aikf.com/ask/resources/images/facialExpression/qq/2.gif\" />",
        "<h3>Test3</h3><img src=\"http://www.aikf.com/ask/resources/images/facialExpression/qq/3.gif\" />",
        "<h3>Test4</h3><img src=\"http://www.aikf.com/ask/resources/images/facialExpression/qq/4.gif\" />",
        "<h3>Test5</h3><img src=\"http://www.aikf.com/ask/resources/images/facialExpression/qq/5.gif\" />",
        "<h3>Test6</h3><img src=\"http://www.aikf.com/ask/resources/images/facialExpression/qq/6.gif\" />",
        "<h3>Test7</h3><img src=\"http://www.aikf.com/ask/resources/images/facialExpression/qq/7.gif\" />",
        "<h3>Test8</h3><img src=\"http://www.aikf.com/ask/resources/images/facialExpression/qq/8.gif\" />",
        "<h3>Test9</h3><img src=\"http://www.aikf.com/ask/resources/images/facialExpression/qq/9.gif\" />"

上下滑动几次后, 表情就各种错位了, 播放速度也不对, view复用的问题

**Comment by mercuryglory** [comment]
img标签中没有宽高的话onFix方法会在图片加载完成前后调用两次，可以通过imageReady来判断
我用这样一个标签测试  <img src="http://www.oschina.net/js/ke/plugins/emoticons/9.gif" alt="9">
是很小的表情图片,并没有被过滤掉,自定义修复时判断height和width不大于500也不顶用,还是占满宽高,请问该怎样解决?

**Comment by zzhoujay** [comment]
OK，我周末会处理的

**Comment by zzhoujay** [comment]
@mercuryglory 
有没有禁用自动修复`autoFix(false)`？没禁用的话自定义修复不会生效。img标签没有height和width属性时会在加载完成前后调用两次onFix，imageReady为true时为已加载，这时应该已经可以获取到真实的宽高。理论上只要设置了`autoFix(false)`就不会出现图片满屏宽的情况（除了`holder.setAutoFix(true)`）

**Comment by mercuryglory** [comment]
好的,非常感谢.确实很好用
我把那个改成判断imageReady为true时才判断是否修复.已经解决了

**Comment by zzhoujay** [comment]
@denghui1010 这个问题定位了很久目前也没找到确切的原因,感觉和Gilde的Gif缓冲池有关,后面解决了会第一时间通知你的

**Comment by denghui1010** [comment]
@zzhoujay ok

**Comment by Lemonqsj** [comment]
这个demo有毒,跑步起来啊....

**Comment by zzhoujay** [comment]
@Lemonqsj demo包的代码很久没更新了，因为只是用来测试用的，跑不起来确实也是有可能的
