### ISSUE TITLE
OpenGLRenderer: Bitmap too large to be uploaded into a texture (3120x4160, max=4096x4096)

### ISSUE THREAD

**Issue by fangshuai0119** [zzhoujay/RichText#38]
图片过大后出现的问题
代码部分：
RichText.from(quanziArticle.getContent()).autoFix(false).fix(new ImageFixCallback() {
            @Override
            public void onFix(ImageHolder holder, boolean imageReady) {
                if (holder.getHeight() < AndroidUtils.getHeight() && holder.getWidth() < AndroidUtils.getWidth()) {
                    holder.setAutoFix(true);
                } else {
                    holder.setHeight(AndroidUtils.getHeight());
                    holder.setWidth(AndroidUtils.getWidth());
                }
            }
        }).into(mArticleContent);

**Comment by zzhoujay** [comment]
@fangshuai0119 能否提供一个大图的链接方便测试

**Comment by fangshuai0119** [comment]
http://static.tme.im/article_1_1471686391302fue

**Comment by zzhoujay** [comment]
ok,我后面会处理的

**Comment by zzhoujay** [comment]
用你给的图片测试了下并没有出现oom,如果已知是大图的话可以使用自定义修复的方法先限制图片的宽高
