### ISSUE TITLE
html li标签未自动换行

### ISSUE THREAD

**Issue by ymcao** [zzhoujay/RichText#41]
html碰到li标签，未自动换行

**Comment by ymcao** [comment]
<p style=\"font-family:Proxima Nova;font-size:14;color:gray\">To determine the applicable shipping rate for items in your Cart:</p ><ol><li style=\"font-family:Proxima Nova;font-size:10;color:gray\">Select Buy to Checkout</li><li style=\"font-family:Proxima Nova;font-size:10;color:gray\">Select or add your shipping address</li></ol><br><p style=\"font-family:Proxima Nova;font-size:12;color:gray\"><b>The total shipping &amp; tax fee will be listed under Order Summary.</b></p>

**Comment by ymcao** [comment]
我的html文本是"<p style=\"font-family:Proxima Nova;font-size:14;color:gray\">To determine the applicable shipping rate for items in your Cart:</p ><ol><li style=\"font-family:Proxima Nova;font-size:10;color:gray\">Select Buy to Checkout</li><li style=\"font-family:Proxima Nova;font-size:10;color:gray\">Select or add your shipping address</li></ol><br><p style=\"font-family:Proxima Nova;font-size:12;color:gray\"><b>The total shipping &amp; tax fee will be listed under Order Summary.</b></p>"

**Comment by zzhoujay** [comment]
Html.fromHtml这个方法好像并不支持列表,后续可能会添加对自定义标签的支持,或者可以尝试使用markdown

**Comment by ymcao** [comment]
使用RichText后 
设置   
 android:ellipsize="middle"
 android:maxLines="3"
 省略号没了

**Comment by zzhoujay** [comment]
文本源为Spanned时使用ellipsize貌似会冲突，我这边测试一个普通的span加上ellipsize直接ANR了
