### ISSUE TITLE
RichText 里Markdown 不支持描点吗

### ISSUE THREAD

**Issue by klzhong69** [zzhoujay/RichText#42]

**Comment by zzhoujay** [comment]
支持这样的语法(不知道是不是你说的锚点)
```
[link][id]
[id]:https://github.com/zzhoujay/RichText/issues/42
```

**Comment by klzhong69** [comment]
android里 不能通过这样跳转
----------------------------------

[说明文字](#jump)
然后标记要跳转到什么位置即可：

<span id = "jump">跳转到这里：</span>

**Comment by zzhoujay** [comment]
这种的话目前确实不支持,而且感觉锚点也不怎么符合Android上的使用习惯,如果有需要可以在[Markdown](https://github.com/zzhoujay/Markdown)中提个issue,后续有空会想想办法的
