### ISSUE TITLE
使用richtext 导致自身的点击事件被屏蔽了

### ISSUE THREAD

**Issue by ymcao** [zzhoujay/RichText#43]
在recylerview 的holder中使用richtext 导致点击到textview区域，点击事件无法响应。

**Comment by zzhoujay** [comment]
确实存在这种问题，而且没法做到部分屏蔽点击事件，在最新的`2.0.11`版本中加入了屏蔽所有点击事件的选项，应该可以解决这个问题

```
RichText.from(text).clickable(false).into(textView)
```
