### ISSUE TITLE
版本编译有问题

### ISSUE THREAD

**Issue by shaycormac** [zzhoujay/RichText#49]
你好，gradle中集成你的最新2.0.13,同步显示v23里面com.android.support/appcompat-v7/23.0.1/res/values-v23/values-v23.xml找不到，我项目中的编译版本和版本工具都是22的，target也是22，升级成23会带来很多问题，想请问一下，可不可以把你的架包版本降低呢？

**Comment by zzhoujay** [comment]
需要降低到多少？22？
