### ISSUE TITLE
多张大图情况下加载有问题

### ISSUE THREAD

**Issue by seasonyuu** [zzhoujay/RichText#51]
测试的内容是知乎手机网页上看到的一个回答
[链接](https://www.zhihu.com/question/20727176/answer/123207440)

实际使用过程中我用来显示的String如下

汉仪喵魂体！&lt;br&gt;自己写了小半年的手写字体刚上线，自我感觉还是值得推荐的！&lt;br&gt;我先给大家图文并茂地讲讲这字儿怎么值得推荐！&lt;br&gt;&lt;img src=&quot;https://pic3.zhimg.com/b6a1334f561eb6f388d5321402ee6c0e_b.jpg&quot; data-rawwidth=&quot;800&quot; data-rawheight=&quot;3266&quot; class=&quot;origin_image zh-lightbox-thumb&quot; width=&quot;800&quot; data-original=&quot;https://pic3.zhimg.com/b6a1334f561eb6f388d5321402ee6c0e_r.jpg&quot;&gt;&lt;img src=&quot;https://pic3.zhimg.com/13fc1f61deeea1e4d5b1fd4d36b30b82_b.jpg&quot; data-rawwidth=&quot;801&quot; data-rawheight=&quot;6071&quot; class=&quot;origin_image zh-lightbox-thumb&quot; width=&quot;801&quot; data-original=&quot;https://pic3.zhimg.com/13fc1f61deeea1e4d5b1fd4d36b30b82_r.jpg&quot;&gt;&lt;img src=&quot;https://pic3.zhimg.com/07fcb9ad57c568d2d41466616fdc6022_b.jpg&quot; data-rawwidth=&quot;801&quot; data-rawheight=&quot;5475&quot; class=&quot;origin_image zh-lightbox-thumb&quot; width=&quot;801&quot; data-original=&quot;https://pic3.zhimg.com/07fcb9ad57c568d2d41466616fdc6022_r.jpg&quot;&gt;&lt;img src=&quot;https://pic1.zhimg.com/a5d631cc0a6c9c5b38c6243ef89e1794_b.jpg&quot; data-rawwidth=&quot;801&quot; data-rawheight=&quot;7352&quot; class=&quot;origin_image zh-lightbox-thumb&quot; width=&quot;801&quot; data-original=&quot;https://pic1.zhimg.com/a5d631cc0a6c9c5b38c6243ef89e1794_r.jpg&quot;&gt;&lt;img src=&quot;https://pic4.zhimg.com/47188b45390ec15b1fd290c2a472d043_b.jpg&quot; data-rawwidth=&quot;801&quot; data-rawheight=&quot;5358&quot; class=&quot;origin_image zh-lightbox-thumb&quot; width=&quot;801&quot; data-original=&quot;https://pic4.zhimg.com/47188b45390ec15b1fd290c2a472d043_r.jpg&quot;&gt;&lt;br&gt;字库加标点接近一万字&lt;br&gt;&lt;br&gt;我的极速是除了吃饭睡觉&lt;br&gt;一刻不停的写&lt;br&gt;一天最多300字&lt;br&gt;极速一天之后第二天就要最少崩溃半天&lt;br&gt;哈哈哈哈哈&lt;br&gt;&lt;br&gt;上半年因为出书有点拖延&lt;br&gt;&lt;br&gt;到临交稿的两个月剩的有点多&lt;br&gt;我只好回老家闭关写&lt;br&gt;（有人做饭啊没有干扰还）&lt;br&gt;有一个半月的时间里&lt;br&gt;每天都&lt;br&gt;从天亮写到天黑&lt;br&gt;从睁眼写到闭眼&lt;br&gt;&lt;br&gt;微信朋友圈还合作什么的&lt;br&gt;啥也不管了不回了&lt;br&gt;&lt;br&gt;特别的酸爽&lt;br&gt;坚持下来之后感觉耐力提升了一百倍&lt;br&gt;&lt;br&gt;之后谁再说什么事儿忍不了抛不下&lt;br&gt;我就特别想说&lt;br&gt;你去抛下一切功名利禄社交合作&lt;br&gt;写俩月字库试试&lt;br&gt;之后什么矫情都没了&lt;br&gt;&lt;br&gt;云淡风轻的&lt;br&gt;&lt;img src=&quot;https://pic1.zhimg.com/00f14a0147fd336a6c34c7817f4f096c_b.jpg&quot; data-rawwidth=&quot;801&quot; data-rawheight=&quot;3178&quot; class=&quot;origin_image zh-lightbox-thumb&quot; width=&quot;801&quot; data-original=&quot;https://pic1.zhimg.com/00f14a0147fd336a6c34c7817f4f096c_r.jpg&quot;&gt;&lt;img src=&quot;https://pic2.zhimg.com/0d1a5113e3ea1bb379b56faeba908f71_b.jpg&quot; data-rawwidth=&quot;600&quot; data-rawheight=&quot;600&quot; class=&quot;origin_image zh-lightbox-thumb&quot; width=&quot;600&quot; data-original=&quot;https://pic2.zhimg.com/0d1a5113e3ea1bb379b56faeba908f71_r.jpg&quot;&gt;啊……&lt;br&gt;最近又有一个字体的想法……&lt;br&gt;还蛮好看……&lt;br&gt;但是写一套太累辣！

**Comment by seasonyuu** [comment]
主要问题是存在几张图片并不能加载出来

**Comment by seasonyuu** [comment]
http://stackoverflow.com/questions/7428996/hw-accelerated-activity-how-to-get-opengl-texture-size-limit 看来是这个问题

**Comment by zzhoujay** [comment]
抱歉之前一直没看到，之前一段时间忙着找工作没时间看，我会尽快处理的

**Comment by zzhoujay** [comment]
额，我这边一直无法重现出你的问题，把VM heap调到32M都没有出现OOM，请问你用的是哪个版本？如果知道是大图可以使用手动修复的方法在加载前先设置图片大小

**Comment by seasonyuu** [comment]
你有看到我第一条评论写的那串HTML字符串吗？就是那个了，并不是OOM，只是部分图片不显示了而已。我用的版本应该是最新的了，直接gradle配置的。我也想加载前设置图片大小，但是由于是抓包的产物，我也没办法控制这方面内容。

**Comment by zzhoujay** [comment]
你那个里面格式都乱了，能传个文件吗

**Comment by seasonyuu** [comment]
我在第一条评论不是放了个链接？？？在一开始那里呢

**Comment by zzhoujay** [comment]
我去你给的链接把那部分源码拿来了，加载后发现确实出现了有些图未加载出来，但是那张图在原网页上好像本来就没有，如下图：
![jietu](https://cloud.githubusercontent.com/assets/10001124/19463030/66f461ac-9523-11e6-8830-392efec83530.jpg)
加载不出的图片的src是`//zhstatic.zhihu.com/assets/zhihu/ztext/whitedot.jpg`，用浏览器打开发现是个1x1的白点，不知是不是Glide不支持加载这么小的图片

**Comment by seasonyuu** [comment]
![device-2016-10-18-181030](https://cloud.githubusercontent.com/assets/8638535/19473443/446845a0-955e-11e6-989b-1fd64f1f571b.png)
我不知道你是怎么显示的…我这边就是显示不出来，代码大概是这个文件这样的而已

[Uploading MainActivity.java.text…]()

**Comment by zzhoujay** [comment]
用你的代码我这边还是没有出现问题图片全部显示出来了，问题应该是图片太大，Android系统不支持加载那么大的图片，在[Glide的issue](https://github.com/bumptech/glide/issues/547)里看到类似的问题了  

因为图片在加载前我这边是无法知道图片真实的大小，所以没法在加载到内存前知道图片的大小，不过可以在加载前用[自定义修复](https://github.com/zzhoujay/RichText/wiki/Manual-fix)来指定宽高

**Comment by seasonyuu** [comment]
你是不是没用真机测试的…

**Comment by zzhoujay** [comment]
确实，我在真机上重现出来了，我会尽快找出问题的

**Comment by zzhoujay** [comment]
问题找到了，是由于View复用时，复用的View的高度比我们第一个item的低太多导致的，解决方法我还得再想想

**Comment by seasonyuu** [comment]
写写你这么用心
