### ISSUE TITLE
RickText长图和RecyclerView混合使用问题

### ISSUE THREAD

**Issue by Mr-GaoSai** [zzhoujay/RichText#57]
RecyclerView 共有20个元素，第一个是长图，以后是普通view。
当第一个view滚动出屏幕，以后往上滚动时，滚动不到第一个item了

**Comment by zzhoujay** [comment]
第一个Item的内容只有图片是么？应该不是item消失了，应该只是图片被回收了，你用的是最新的版本吗？如果是的话试试上一个版本有没有这个问题，方便的话把测试的数据发下我来定位下问题

**Comment by Mr-GaoSai** [comment]
不是只有图片，还有其他数据。奇葩问题是：当我回到第一个时，RecyclerView又滚回最后一个了
`<div class=\"topic_content\" itemprop=\"articleBody\">\r\n        <div class=\"markdown-text\">\r\n        <h2>前言</h2>\r\n<pre class=\"prettyprint\"><code>本来要趁G20的喜庆气氛发布这个版本的,而且是nutz公开发布7周年,nutzcn社区上线1周年,但台风来了,被吹成了SB.\r\n\r\n月初,我(wendal)组织了一次长达4小时斗鱼直播(nutz.cn的内存泄漏排除),收看人数随着时间的推移正比例下降,\r\n最终收入鱼丸0个和鱼翅0根,妥妥的稳定0收入.最终,在睡醒一觉之后,怒删几个依赖库,解决了.\r\n随机调查了2名群众, 35%的群众表示,没有球没有肉,全是硬货太难啃,最终也没高潮,必须差评!!!\r\n\r\n另外,有小伙伴投诉说最近nutz刷版本很快啊,实不相瞒,当前的发布周期就是2-3个月,我觉得不算快枪手了.\r\n\r\n这次,我们集中力量完成了dao层的几个重要更新: #1116 读写分离,#1117 拦截器机制,#1119 支持存储过程的出参\r\n</code></pre><h2>与1.r.57.r3的兼容性</h2><p>这个版本的兼容性,主要是DaoRunner的实现类NutDaoRunner的变化导致的.</p>\r\n<ul>\r\n  <li>判断是否开启自动事务,以前是NutDao负责,现在由NutDaoRunner负责 -- 如果自定义NutDaoRunner的话,改为复写其{_run}方法即可</li>\r\n  <li>SQL日志的打印,现在由DaoLogInterceptor负责 -- 与daocache配合时的日志有变化,但是对功能没有任何影响. 详情看[issue1137 https://github.com/nutzam/nutz/issues/1137]</li>\r\n</ul><h2>主要变化:</h2>\r\n<ul>\r\n  <li>add: #1116 Dao读写分离</li>\r\n  <li>add: #1117 Dao拦截器机制</li>\r\n  <li>add: #1119 支持存储过程的出参</li>\r\n  <li>add: #1121 支持vue-resource的X-HTTP-Method-Override</li>\r\n  <li>fix: #1134 SimpleDataSource不兼容Mysql6.0驱动</li>\r\n  <li>fix: #1114 Http轻客户端的Session维持</li>\r\n  <li>fix: #1109 Mvc前置表单列表的索引顺序不对</li>\r\n</ul><h2>关联项目更新:</h2>\r\n<ul>\r\n  <li>add: daocache支持dao拦截器模式配置</li>\r\n  <li>add: dubbo插件,兼容原生dubbo配置</li>\r\n  <li>add: apidoc插件</li>\r\n  <li>add: SfntTool插件,字体文件精简,用于PDF字体内嵌</li>\r\n  <li>update: views插件支持pdf view和velocity layout</li>\r\n  <li>update: sigar符合新版nutz插件的命名规则</li>\r\n  <li>update: 大鲨鱼写的 <a href=\"https://github.com/Wizzercn/NutzWk\" target=\"_blank\">https://github.com/Wizzercn/NutzWk</a> 3.2.7</li>\r\n  <li>update: 單純願望 <a href=\"https://github.com/Kerbores/NUTZ-ONEKEY\" target=\"_blank\">https://github.com/Kerbores/NUTZ-ONEKEY</a> 2.0</li>\r\n  <li>update: 悟空 <a href=\"https://github.com/wukonggg/mz-g\" target=\"_blank\">https://github.com/wukonggg/mz-g</a> 0.6.3</li>\r\n</ul>\r\n\t\t</div>\r\n      </div><img width=\"258\" height=\"186\" title=\"点击查看源网页\" class=\"currentImg\" style=\"left: 330.5px; top: 24.5px; width: 258px; height: 186px; cursor: pointer;\" onload=\"alog &amp;&amp; alog('speed.set', 'c_firstPageComplete', +new Date); alog.fire &amp;&amp; alog.fire('mark');\" src=\"http://img2.imgtn.bdimg.com/it/u=2643681278,706636134&amp;fm=21&amp;gp=0.jpg\" log-rightclick=\"p=5.102\"><div id=\"J-detail-content\"><img alt=\"\" src=\"http://img10.360buyimg.com/imgzone/jfs/t2719/53/693438809/405912/957c1efa/5721e109N8ad86029.jpg\"> \n<img alt=\"\" src=\"http://img10.360buyimg.com/imgzone/jfs/t2836/30/707249522/270588/840d428a/5721e108Ne667230f.jpg\"> \n<img alt=\"\" src=\"http://img10.360buyimg.com/imgzone/jfs/t2305/211/1222246162/89571/4ce4f9a1/56496ac7N982aa001.jpg\"> \n<img alt=\"\" src=\"http://img10.360buyimg.com/imgzone/jfs/t2695/76/715579111/331050/cf2ae9f9/5721e10aNd690b026.jpg\"> \n<img alt=\"\" src=\"http://img10.360buyimg.com/imgzone/jfs/t2341/288/2958575364/740490/9678e90f/5721e10bNf923ebaa.jpg\"> \n<img alt=\"\" src=\"http://img10.360buyimg.com/imgzone/jfs/t2776/164/715581717/852142/2fa4714f/5721e10bN04e38f08.jpg\"> \n<img alt=\"\" src=\"http://img10.360buyimg.com/imgzone/jfs/t2104/197/2936780208/316761/f3051b63/5721e10cN1b74089c.jpg\"><br></div>`

**Comment by zzhoujay** [comment]
我试了下，并没有出现你说的第一个item消失的情况，你确定是由于使用了RichText才导致的这个现象吗？

**Comment by Mr-GaoSai** [comment]
当切换回WebView时正常。换成RichText就不正常了

**Comment by zzhoujay** [comment]
能把你测试出现问题的代码发下吗

**Comment by zzhoujay** [comment]
现在做了一些处理后在`2.1.0`版本在ListView可以正常使用了，RecyclerView任然存在问题，可能和RecyclerView的复用机制和布局机制有关，我后续会继续研究的。
