### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by wm1993** [zzhoujay/RichText#58]
这个库好像有内存泄露情况，特别是加载有图片的Html文本，

**Comment by wm1993** [comment]
"<span style=\"color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;line-height:30px;background-color:#FFFFFF;\"><span style=\"font-size:12px;\">日前，南方电网公司发布《2014年社会责任报告》显示，南方电网近年来积极促进清洁电源特别是水电、风电、太阳能等可再生能源发展，电源结构持续优化，2014年南方五省区内非化石能源发电量占比提至45.5%，大幅高于24.7%的全国平均水平。</span></span><span style=\"color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;line-height:30px;background-color:#FFFFFF;\"></span> <div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t最新电力统计数据显示，2015年上半年，全社会用电量累计26624亿千瓦时，同比增长1.3%.6月份，全社会用电量4723亿千瓦时，同比增长1.8%.全社会用电量稳步回升。<br/>&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;text-align:center;\">\t<img alt=\"环境倒逼能源结构调整 新型能源市场将不断拓展\" src=\"http://news.huasuhui.com/uploadfile/2015/0818/20150818104218928.jpg\" /> </div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t但是，据数据显示，2015年上半年，全国煤炭产量17.89亿吨，同比下降5.8%.降幅比2014年的全年数据扩大了整整一倍。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t向来与煤炭消费、生产数据联系紧密的发电量却出现了0.6%的微增，而以煤炭为主的火电发电同比下降3.2%.</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t对此，行业人士称，数据的背道而驰，与能源结构的调整相关。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t我国是世界上最大的煤炭生产国和消费国。由于我国煤炭储量丰富，煤炭的一次性消耗对于推动我国经济增长起到了巨大作用。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t而且，火力发电企业是能源消耗型企业，主要消耗煤炭、石油、液化气，而煤炭作为火电企业最主要的原料，占发电成本的60%-70%.</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t<b>环境倒逼能源结构调整</b> </div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t据2015年BP《世界能源统计年鉴》显示，2014年全球经济增长与2013年相当，但一次能源消费增长却明显下降，世界煤炭产量下降0.7%，其中跌幅较大的是中国（-2.6%）。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t从数据中不难看出，我国能源结构正在发生调整。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t卓创资讯分析师刘杰在接受记者采访时表示：“我国对煤炭的消费主要是涌向电力行业，有约60%的煤炭用来发电。但是，煤炭发电时，通过粗放的燃烧，能源利用率只有30%-50%左右。”</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t煤炭作为一次能源，与石油、天然气等非固体能源品种相比，在产生相同多能量的前提下，煤炭排放出的二氧化碳（CO2）、二氧化硫（SO2）、氮氧化物（NOx）、颗粒物（烟粉尘或一次PM2.5）、汞（Hg）等重金属等污染物要更多。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t“煤炭资源附加值低，使用后对环境污染也比较严重，目前我国正致力于降低煤炭在一次性消费能源中的占比，扩大包括风电、核能等清洁能源的利用。”中宇资讯分析师关大利在接受记者采访时表示。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t事实上，随着全球人口和经济规模的不断增长，使用煤炭等含碳高的能源带来的环境问题不断被人们所认识。这类能源过度消耗所引发的温室效应、大气污染等问题正日益影响人们正常的生活环境，破坏生态平衡。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t“以煤炭为主的传统资源消耗模式正逐步转向以油气资源为特点的能源模式。”卓创资讯分析师刘新伟向记者表示：“太阳能、核能等新型能源将成为未来主力。”</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t据中电联数据显示，2015年上半年，全国主要电网统调发电量比上年同期增长0.6%（日均），最高发电电力合计72644万千瓦，比上年同期增长1.5 %.其中，火电20879亿千瓦时，同比下降3.2%；水电4234亿千瓦时，同比增长13.3%；核电772亿千瓦时，同比增长34.8%.</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t另外一组大唐国际发电股份有限公司发布的数据显示，2015 年上半年火电机组发电量同比降低约5.19%；水电机组发电量同比增加约18.06%；风力及光伏机组发电量同比增加约 9.63%.</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t对此，行业人士分析称，在国际碳减排形势与国内经济增长的双重压力下，低碳战略势在必行。减少不可再生能源的消费，大力开发和利用清洁、可再生能源已成为我国能源发展的重要部分。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t同时，记者了解到，我国作为能源消费大国，降低煤炭使用量、扩展清洁能源的获取渠道以及利用，早已纳入国家能源战略体系。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t2013年9月，国务院正式公布的《大气污染防治行动计划》（以下简称《行动计划》），《行动计划》明确规定，到2017年煤炭占能源消费总量比重降到65%以下，京津冀、长三角、珠三角等区域力争实现煤炭消费总量负增长，煤炭需求空间将进一步压缩。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t2014年底，国务院颁布的《能源发展战略行动计划2014-2020》指出，我国优化能源结构的路径是：降低煤炭消费比重，提高天然气消费比重，大力发展风电、太阳能、地热能等可再生能源，安全发展核电。到2020年，非化石能源占一次能源消费比重达到15%；天然气比重达到10%以上；煤炭消费比重控制在62%以内；石油比重为剩下的13%.</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t对于我国能源结构调整，行业内普遍认为主要有三个方向，一是提高低碳非化石能源比重，降低化石能源比重，实现增量调整；二是提高石油、天然气在化石能源比重，降低煤碳的比重，实现存量调整，并实现化石能源清洁化；三是提高水电、核电、太阳能发电、生物质能发电的比重，降低煤电（火电） 比重。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t<b>政策扶持带动技术突破</b> </div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t而实现这三个方向的目标，仅依靠能源企业自身显然有所不足。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t重要的是，我国能源消费结构与美国、欧洲国家以及世界平均水平都存在很大差异，原油、天然气占据一次能源消费比重偏低，而煤炭消费比重偏高，这和我国多煤、贫油、少气的具体国情是紧密相关的。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t据2014年BP《世界能源统计年鉴》数据显示，天然气在我国一次能源消费中占5.1%，不足世界平均水平25%；核能只有0.88%，不足世界平均水平的20%；只有水电达到7.23%，略高于世界平均水平的6.72%.</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t此外，能源短缺是全球性的问题，为此各国都在加强对新能源、清洁能源的探索。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t关大利表示，如何突破在能源开采利用过程中技术性问题已至关重要。他认为，不同于发达国家的丰富资源，我国在天然气、风电等领域的开发利用成本相对较高，同时在能源储备方面仍存在技术上的问题。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t一位不愿透露姓名的业内人士张军（化名）告诉记者：“风能作为火电、水电之后的第三发电能源体系，目前占比还是很低。同时，风能发电没有形成大规模，发电量较煤电等传统发电较少。相比之下，太阳能的比重更低，但是太阳能在未来发展空间较大。”</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t张军还表示，与发达国家相比，总体上我国的生产工艺和水平与国外差距不大。但是，我国风能发电还没有掌握个别的核心技术。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t张军表示，走好能源可持续发展道路，国家需要解决政策支持力度稳定性以及利益机制协调的问题。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t在强化能源战略地位的同时，加强与国外拥有先进能源开发技术国家的合作至关重要。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t据了解，中国至2014年底已与世界50多个国家确立了战略伙伴关系，包括政治、经济、技术、文化等和能源合作关系，能源合作即石油、天然气、风能、太阳能、核能的合作关系。石油、天然气重点与中东、中亚、非洲、俄、美、委等地区与国家合作。核能、核电与法国、美国、俄、加合作，消化和吸收改进并自主化发展。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t观察人士预测，在国家利好政策的大力扶持之下，我国在以核能为代表的清洁能源开发和利用领域将会取得核心技术的突破，实现能源结构的转型和调整。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t<b>可借鉴“他山之石”</b> </div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t今年年初，欧盟委员会召开会议公布了能源联盟的战略纲领，不仅是欧盟，美国作为西方大国，在能源、科技发展道路上已然处于领先地位。然而，即便是这样的能源大国，近年来，美国政府仍积极出台法律条文，大力发展清洁可再生能源。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t中投顾问能源行业研究员宋智晨向记者讲道：“发达国家积极推动新能源产业的发展，新能源在能源总量中的比重要高于我国，其发展经验值得借鉴。”</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t第三方研究报告显示，美国将天然气、<a href=\"http://news.huasuhui.com/index.php?m=search&c=index&a=init&typeid=1&siteid=1&q=%E9%A1%B5%E5%B2%A9%E6%B0%94\" target=\"_blank\">页岩气</a>作为重点能源进行开发，从而有效地压缩了石油、煤炭在能源构成中的比重。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t业内人士分析，这样不仅减少了美国对中东地区石油依赖程度，弱化了本土石油行业的风险，从而确保了美国能源安全。同时，新的行业领域意味着更多的就业岗位，这对于降低无业人口比重，巩固社会安定大有裨益。此外，清洁能源利用所产生的经济效益与社会效益将为美国经济可持续发展奠定了良好基础。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t专业人士指出，美国能源发展道路非常清晰明确，其以经济可持续发展为根本目的而采取的一系列措施值得肯定，这对我国能源发展战略的制定具有极大的借鉴意义。他强调，我国作为发展中国家，应当重点学习借鉴美国能源发展模式，加快能源结构转型，大力开发利用新能源，尤其是核能、风能、光伏等储量较大、与环境相对协调的能源，减少对煤炭等传统能源的依赖，走能源可持续发展道路。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t值得注意的是，不同于美国丰富的风力、页岩气储备，俄罗斯区域内密集的天然气资源等，我国应该积极勘测能源储备，制定合理的开发利用发展模式，走具有中国特色的能源发展道路。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t在借鉴发达国家能源发展经验的基础上，对于我国的能源发展，宋智晨表示，首先，政府推动完善新能源立法和规划并对新能源产业进行长期的资金支持；其次，因地制宜重点发展生物能源和新能源汽车并推动与之相关的产业发展；最后，积极引导对新能源产业的消费需求并大力培育新能源企业的自主创新能力。</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t&nbsp;</div><div style=\"margin:0px;padding:0px;color:#585858;font-family:arial, 'Microsoft YaHei', u5b8bu4f53;font-size:16px;background-color:#FFFFFF;\">\t宋智晨强调，煤炭和石油等化石能源虽然对环境的破坏作用比较大，但在未来一段时间内依然是我国的主要能源，还需要继续开发和利用，不过在能源总产量中的比重会逐年递减，对环境的污染方面也会加以改进。由于太阳能、风能、核能、氢能等新型能源的储量大、可再生强且清洁环保，在未来将会得到积极的开发和利用。</div>"

**Comment by zzhoujay** [comment]
刚刚分析了下，确实有一些地方没处理好，下个版本会修复，不过那些图片主要还是Glide持有的引用，Glide自身应该也有相应的调度来解决

**Comment by zzhoujay** [comment]
在`2.1.0`版本中解决了我所发现的一些内存泄露的问题

**Comment by wm1993** [comment]
最好加载图片能够让使用者自定义，避免重复的第三方依赖，减少app体积。

**Comment by zzhoujay** [comment]
额，其实RichText这个库最主要解决的问题就是图片加载和后续处理的问题，如果你需要只是富文本的解析的话Html解析可以直接使用`Html.fromHtml`，markdown的话可以使用[markdown解析器](https://github.com/zzhoujay/Markdown)来自己做
