### ISSUE TITLE
Error:(39, 36) 错误: 程序包com.zzhoujay.richtext.target不存在

### ISSUE THREAD

**Issue by stevefat** [zzhoujay/RichText#62]
貌似你没有上传这个包呀，

**Comment by zzhoujay** [comment]
额，上传了啊，是用的`2.1.0`版本么？我这边用Gradle也可以找到的

**Comment by stevefat** [comment]
在richtext 这个库里面没有呀

**Comment by donal-tong** [comment]
源码没有

**Comment by donal-tong** [comment]
![image](https://cloud.githubusercontent.com/assets/2238211/19715936/572a7d9c-9b8b-11e6-9992-6c9a50f5015b.png)

**Comment by zzhoujay** [comment]
理解你意思了，上次不小心把target这个包给ignore了，现在推上去了。
