### ISSUE TITLE
大神，我的图片一直不显示，是怎么回事？

### ISSUE THREAD

**Issue by q460468765** [zzhoujay/RichText#63]
textview是放在RecyclerView的item里面的，直接通过
compile 'com.zzhoujay.richtext:richtext:2.1.0'引入的RichText
字符串：
 "<p>试用员工提前三天，正式员工提前三十天以书面形式向所在部门离职申请，所有流程都是在NCOA上进行，首先是离职申请，通过之后是离职交接，NCOA离职交接流程如下：<br />\r\n<br />\r\n<img alt=\"\" src=\"http://mutone.fangte.com/V2/Manage/UpLoadFile/httpfile/10033073/image/png/2016/09/05/122805383318639.png\" style=\"height:256px; width:480px\" /><br />\r\n<br />\r\n员工未办理各项交接手续，不辞而别的，或超假旷工五个工作日以上者，视为自动离职，自动离职的员工不予发放工资，并且终生不予回聘。</p>"

**Comment by q460468765** [comment]
"<p>试用员工提前三天，正式员工提前三十天以书面形式向所在部门离职申请，所有流程都是在NCOA上进行，首先是离职申请，通过之后是离职交接，NCOA离职交接流程如下：<br />\r\n<br />\r\n<img alt=\"\" src=\"http://mutone.fangte.com/V2/Manage/UpLoadFile/httpfile/10033073/image/png/2016/09/05/122805383318639.png\" style=\"height:256px; width:480px\" /><br />\r\n<br />\r\n员工未办理各项交接手续，不辞而别的，或超假旷工五个工作日以上者，视为自动离职，自动离职的员工不予发放工资，并且终生不予回聘。</p>"

**Comment by q460468765** [comment]
有<img>标签怎么发出来就没有了

**Comment by q460468765** [comment]
[richtext.txt](https://github.com/zzhoujay/RichText/files/557793/richtext.txt)

**Comment by q460468765** [comment]
我试过了，放在项目其他的TextView上可以显示，但是放在RecyclerView的item布局里面的TextView就不行。什么原因

**Comment by q460468765** [comment]
找到了上面的原因了，因为item里面的textview设置的是wrap_content，改成match_parent就可以，但是放在RecyclerView里面好多问题啊，图片fix没用，而且点击事件也没用。

**Comment by zzhoujay** [comment]
额，链接的点击事件确实有一点没处理好，已在`2.1.1`版本里修复，图片若要手动fix，需要先调用`autoFix(false)`再设置手动fix回调

**Comment by q460468765** [comment]
我这里还是不稳定，放在recycerView里面，手动fix，加上了antoFix(false)，还是有时候可以fix，有时候不可以fix，而且fix失败的话点击事件也失效，fix成功的话才有点击事件~而且大部分都是不可以fix。
 RichText.fromHtml(item.getContent()).autoFix(false)
                .fix(new ImageFixCallback() {
                    @Override
                    public void onFix(ImageHolder holder, boolean imageReady) {
                        if (holder.getWidth() > 400 && holder.getHeight() > 400) {
                            holder.setAutoFix(true);
                        }
                    }
                })
                .clickable(true)
                .imageClick(new OnImageClickListener() {
                    @Override
                    public void imageClicked(List<String> imageUrls, int position) {
                        LogUtils.e(imageUrls.get(position));
                        Toast.makeText(context, imageUrls.get(position), Toast.LENGTH_SHORT).show();
                    }
                })
                .into(tv_content);

**Comment by zzhoujay** [comment]
理论上autoFix为false，且设置了fixCallback的话肯定是会被调用的，如果不能被调用那么图片应该也显示不了才对

**Comment by zzhoujay** [comment]
fixCallback会在图片加载前后调用两次，如果没被调用则说明可能是源文本格式有问题，没有识别为img标签，没有进行图片加载操作

**Comment by q460468765** [comment]
嗯，好吧，我这里确实是有时候可以fix，而且是fixed情况下才能点击，没有修复图片的时候点击也不生效，概率事件

**Comment by q460468765** [comment]
只有“sync project”后第一次运行的时候是正常的，如果我再直接覆盖运行apk，就失效了，我再重新“sync project”后运行又是正常的，这是什么原因呢~

**Comment by zzhoujay** [comment]
开instance run没？难道说缓存问题？我这边测试都是没有开instance run的，这个问题很迷啊！
