### ISSUE TITLE
什么时候支持富文本编辑的edittext

### ISSUE THREAD

**Issue by donal-tong** [zzhoujay/RichText#65]
如题

**Comment by zzhoujay** [comment]
我打算新开一个项目做富文本编辑，这个项目暂时只做解析，后续开发完成后再看能不能合并下

**Comment by donal-tong** [comment]
我也来参与，可以么？

**Comment by zzhoujay** [comment]
可以的，等我建项目后把你加进去

**Comment by zzhoujay** [comment]
[RichEditor](https://github.com/zzhoujay/RichEditor)
建了个项目，到时候我推了代码后你fork吧

**Comment by zzhoujay** [comment]
话说加个QQ吧，方便交流`1582519486`

**Comment by donal-tong** [comment]
加你了
