### ISSUE TITLE
能加载本地图片吗

### ISSUE THREAD

**Issue by xesygao** [zzhoujay/RichText#66]

**Comment by zzhoujay** [comment]
应该是可以的，因为图片加载是有Glide做的，所以理论上是支持的，把图片的路径填本地路径，再加上存储访问权限，应该是可以的

**Comment by xesygao** [comment]
好的谢谢。
还有个问题，在listview中，向上滑的时候，如果上一个item有图片，listview会一下子跳到上一个item（显示上一个item的全部图片）

**Comment by zzhoujay** [comment]
之前确实是有这个这个问题的，后来改了下后测试在ListView中应该是正常的，不过RecyclerView中目前确实存在此类问题（详情可以看这个issue[RickText长图和RecyclerView混合使用问题](https://github.com/zzhoujay/RichText/issues/57)），你现在用的是最新版本吗？

**Comment by xesygao** [comment]
对的，用的是2.2.1，我用的是listview

**Comment by zzhoujay** [comment]
能发下测试数据吗？方便的话希望可以发下测试代码，方便定位问题
