### ISSUE TITLE
zzhoujay

### ISSUE THREAD

**Issue by q460468765** [zzhoujay/RichText#67]
之前有说过在RecyclerView里面fix没作用且点击没效果的问题，然后我debug，发现有走ImageFixCallback两遍，在debug模式下正常图片正常显示且可以点击，但是直接运行图片又不会被fix也点击不了~这会是什么原因啊，而且wiki里面说的异步也没有这个方法·

**Comment by q460468765** [comment]
方便的话加下我QQ呗，就是我的名字上的，我是隔几天回过头来搞这个问题的，每次都想一次解决

**Comment by zzhoujay** [comment]
异步的方法很久前就被标记为`Deprecated`了，在最新的几个版本已经被去掉了，异步的话还是让调用者来做吧
