### ISSUE TITLE
代码高亮

### ISSUE THREAD

**Issue by YunrZhao** [zzhoujay/RichText#68]
`请问一下，RichText在解析Html时支持代码高亮吗？啊，我在那个<pre>标签上已经折腾好久了。求指点`

**Comment by zzhoujay** [comment]
代码高亮并不支持，不过要实现pre标签的功能是可以的，我会尽快实现的，到时候通知你

**Comment by YunrZhao** [comment]
好的，谢谢你了。pre在webview中很难适配。让我绞尽脑汁折腾了两周还是无果。期待你的成功！

**Comment by zzhoujay** [comment]
试了下，单纯使用系统Html类没办法做到这点，我准备试着自己写个Html解析器来做

**Comment by YunrZhao** [comment]
好，谢谢你。

**Comment by zzhoujay** [comment]
抱歉，最近比较忙，暂时没有精力和时间开发新功能，目前只能抽时间修复bug
