### ISSUE TITLE
同样的图片 显示效果不一样。

### ISSUE THREAD

**Issue by Xiemarc** [zzhoujay/RichText#76]

**Comment by Xiemarc** [comment]
我的使用代码是

**Comment by Xiemarc** [comment]
`  RichText.fromHtml(textImageTitle).autoFix(false).fix(new ImageFixCallback() {
            @Override
            public void onFix(ImageHolder holder, boolean imageReady) {
                if (imageReady) {
                    //拿到图片了
                    int width = holder.getWidth();
                    int height = holder.getHeight();
                    //得到图片真实的款高比例，然后等比例缩放
                    if (width * 3 > ScreenUtils.getScreenWidth(mContext)) {
                        //如果宽度大于屏幕宽度，就设置成屏幕宽度
                        holder.setWidth(ScreenUtils.getScreenWidth(mContext));
                    } else if (width < 20) {
                        holder.setWidth(20);
                    }
                    //高度进行等比例缩放
                } 
            }
        }).placeHolder(R.drawable.trans_bg).into(title);`

**Comment by zzhoujay** [comment]
详细描述怎么没了

**Comment by Xiemarc** [comment]
同样的source，在不同尺寸的手机上面显示，A手机都能加载到图片，B手机加载不到图片，显示的图片大小不一样。没有拿到图片的只显示了占位图。已经设置占位图大小了。但是还是很大的占位图。

**Comment by Xiemarc** [comment]
http://ogrzkg62w.bkt.clouddn.com/7%E7%89%9B.png

**Comment by zzhoujay** [comment]
1.不同手机加载图片问题。排除了网络或者权限之类的其他原因了吗？
2.显示的图片大小不一样是同一个source在同一台设备还是不同设备上？
3.占位图，已经找到问题所在，会尽快修复。

**Comment by Xiemarc** [comment]
1.网络加载问题初步判断是6.0 权限问题。
2.17号晚更新版本是否是解决的占位图问题

**Comment by Xiemarc** [comment]
1.   是不是6.0权限问题，但是在vivo的4.4上面问题一样。
2.  占位图是不是
private RichText(String sourceText) {
        this(true, sourceText, new ColorDrawable(Color.LTGRAY), new ColorDrawable(Color.GRAY), RichType.HTML);
    }
这里的问题。

**Comment by Andecy** [comment]
@Xiemarc 应该不是，用的5.1

**Comment by Xiemarc** [comment]
@Andecy  glide显示占位图的原因？

**Comment by Xiemarc** [comment]
@zzhoujay 另外看到昨晚更新了，更新什么内容了。 public void onFix(ImageHolder holder) {}去掉imageReady了？
出现的问题是通过imagehoder.getImageState()拿到各个状态 去做处理。但是是依照加载中的那个设置处理的
  case 1://加载中
                        holder.setWidth(50);
                        holder.setHeight(50);
                        break;
                    case 2://图片加载成功
                        //加载成功
//                        setHolderImageConfig(holder);
                        int width = holder.getWidth();
                        int height = holder.getHeight();

加载成功不进行的

**Comment by zzhoujay** [comment]
@Xiemarc 昨晚的更新修复了占位图的问题，然后ImageFixCallback的回调会被调用多次，每次ImageHolder的imageState属性都不一样，分别会在 INIT：开始加载前，LOADING：真正加载，READY：加载成功，FAILED：加载失败。

在INIT的回调中设置holder的宽高是设置给GLide的，LOADING的回调中设置的宽高是给placeHolder图片的，READY的回调是设置给最终显示的图片设置宽高，FAILED回调是用于设置出错占位图设置宽高

**Comment by Xiemarc** [comment]
@zzhoujay  谢谢了。我仔细看下

**Comment by Andecy** [comment]
现在还有个情况，就是我在ImageFixCallback中不判断ImageState，修改全部的图片大小，发现有些图片就显示不出来了，一直是深灰色，如果不fix，就100%成功显示

**Comment by zzhoujay** [comment]
@Andecy 你的意思是fix会导致某些图片加载不出来吗？

**Comment by Andecy** [comment]
@zzhoujay 刚才试了下，之后在resize的情况下才会
```java
//只要有这个：部分不显示
holder.setWidth(100);
holder.setHeight(100);

//只有这个：显示
holder.setAutoPlay(true);
```

**Comment by zzhoujay** [comment]
@Andecy 不是很懂什么情况啊，发下代码和数据我来试试

**Comment by Xiemarc** [comment]
@zzhoujay  现在确实是显示不出来图片了。。全都显示占位图了。。

**Comment by zzhoujay** [comment]
@Xiemarc 你现在用的哪个版本呢？全部图片都显示不出来了吗？显示占位图是指placeholder还是errorImage？图片本身是没有问题的吗？

**Comment by zzhoujay** [comment]
@Xiemarc 开启Instance Run没有？关闭试试
