### ISSUE TITLE
大图第二次加载不出

### ISSUE THREAD

**Issue by chenwulue** [zzhoujay/RichText#78]
`String meTest = "上<br><img src=\"http://api.res.mojing.com/avatar/20161118/C51D7FFF9BDEC09D240D9273CAF299C1.jpg\"/>下";`
加载这段富文本，那张图，第一次可以加载出来，返回再加载，就显示不了了。而且滑动很不流畅

**Comment by zzhoujay** [comment]
滑动不流畅？在ListView、RecyclerView中？如果只是单个TextView的话在TextView外面套个ScrollView可以解决滑动问题

图片第二次显示不出来应该是被回收掉了，后续会想办法解决

**Comment by chenwulue** [comment]
用的是你的Demo的MainActivity里面
我就`private final String meTest = "上<br><img src=\"http://api.res.mojing.com/avatar/20161118/C51D7FFF9BDEC09D240D9273CAF299C1.jpg\"/>下";`
然后`RichText.from(meTest).clickable(true).url...`

**Comment by zzhoujay** [comment]
那出现滑动卡顿的问题应该是图片太大了，你测试机内存多大？

**Comment by zzhoujay** [comment]
在`2.2.2`版本中在图片加载前对图片进行了压缩，你试试看问题还存在没
