### ISSUE TITLE
大的gif显示不了。。。

### ISSUE THREAD

**Issue by chenwulue** [zzhoujay/RichText#81]
测试了用这张图  显示不出来
http://api.res.mojing.com//forum//20161129//BBF80DD33100C50C098D0240EEE484FA.gif

**Comment by zzhoujay** [comment]
试了下，是Glide的问题，可能是你这种图片比较特殊，Glide没有进行相应的处理，我也没啥办法

<img width="725" alt="qq20161129-0 2x" src="https://cloud.githubusercontent.com/assets/10001124/20716465/480f05ae-b68d-11e6-9c52-5d5bd7b2b7fe.png">
