### ISSUE TITLE
图片加载出错

### ISSUE THREAD

**Issue by chenwulue** [zzhoujay/RichText#85]
不知道是不是内部glide缓存问题，有时候会显示成另一张图...

**Comment by chenwulue** [comment]
能不能抽离出一个ImageLoader接口呢，然后我们自己用自己的图片加载库来显示图片

**Comment by zzhoujay** [comment]
额，后面会考虑加一个

如果这个问题是随机发生的话极有可能是Instance Run的问题，有没有用Instance Run？

**Comment by chenwulue** [comment]
没有用Instance Run，没法找到重现的步骤
但是一出现就一直出现
大概步骤是 我一个activity，联网获取的数据，这次加载的imgUrl1，下次加载了imgUrl2，可能下次加载imgUrl3就显示了imgUrl1的图片了，这时候每次加载imgUrl3都是显示imgUrl1  但是再过个几分钟，有可能是把应用关了重开，就没问题了

**Comment by zzhoujay** [comment]
是只有图片会出现这种问题是吧？文本啥的都正常是吧？

**Comment by chenwulue** [comment]
对 只是图片

**Comment by zzhoujay** [comment]
好，我先把图片加载接口开放出来，你试试你自己的加载方式

**Comment by chenwulue** [comment]
嗯  最主要这个不是必现bug，我今天就一直没出现，昨晚出现得比较频繁，也是比较难测出来。。

**Comment by zzhoujay** [comment]
在`2.3.0`版本中已经开放了自定义图片加载器的接口

```
RichText.from(text).imageGetter(yourImageGetter).into(textView);
```

**Comment by zzhoujay** [comment]
在最新`2.3.2`版本里还有这个问题吗？使用自定义图片加载器还存在问题吗？

**Comment by itdais** [comment]
@zzhoujay 
报错位置是 getDrawer(DefaultImageGetter.java:124)行

**Comment by chenwulue** [comment]
@zzhoujay 还是用着你的加载器，一直没出现问题，可能是上次编译器的问题吧

**Comment by itdais** [comment]
@zzhoujay 
图片找不到就崩溃了  报错位置是 
getDrawable(RichText.java:339)
getDrawer(DefaultImageGetter.java:124)行

**Comment by zzhoujay** [comment]
@itdais `2.3.3`版本目前还不稳定，还没有经过很多测试，现在先用`2.3.2`版本吧。

能把你这次报错的详细信息发一些吗，方便定位问题

**Comment by zzhoujay** [comment]
@chenwulue 好的👌

**Comment by zzhoujay** [comment]
@itdais 或者发一下你的测试数据

**Comment by NicodeLee** [comment]
辛苦，图片加载有时候也有加载不出的问题，项目的demo也是。
我测试过公司wifi（无显示）跟4G（正常）
