### ISSUE TITLE
1. 解析性能问题 2. 主线程解析问题 3. 列表中抖动问题

### ISSUE THREAD

**Issue by yqpan1991** [zzhoujay/RichText#86]
看了并且使用了楼主的Markdown实现，整体的质量还可以，不过目前发现的几个问题如下：
1. 实现部分使用了大量的递归，效率上应该是不高的
2. RichText的实现想法很好，但是在主线程解析这个内容，可能会导致卡顿，个人测试，200字的十行左右的markdown，在360N4 android6.0的手机上，耗时需要20ms左右，所有目前来看，不建议这么来实现。
因而考虑在子线程来实现，但是单纯的在子线程解析，也会有其它的问题，比如说，楼主已经提到的，需要在textview 的draw之后，才能使用，也就是textView onLayout之后，才能使用，因而，我在实际开发中，并没有按照楼主的RichText来封装。
根据这几点原因，实际开发中，我是这么做的，开启一个异步线程，采用提前加载的方式，由于需要TextView的onLayout之后（部分span的实现，需要依靠这个，比如说CodeSpan），因而在Layout布局中，隐藏了一个TextView，监听onLayout之后，开启了一个异步线程去解析，解析完成后，存放到Cache中。但是可能提前加载有拦截不到的情况，所以，在RichText中，做了补偿逻辑，如果cache中没有这个数据，便再次去异步加载数据。
在列表中，如果单纯采用异步加载，却没有提前拦截数据去加载，会导致listview或者RecyclerView的抖动，因为在复用item时，textview中自身已经有了内容，而此时异步解析回来数据后，还是要设置给Item，这次设置，会导致抖动，尤其是存在图片的情况下，是特别明显的。
关于图片的解析和展示中，也是有问题的，图片需要提前占位处理，并且图片的大小和展示的大小，需要相同，要不然，图片在加载出来后，还是存在抖动的情况。
有空时，可以把我的实现，提交一个merge request。
不过还是感谢楼主实现的内容，，我的qq是280853071，欢迎交流

**Comment by zzhoujay** [comment]
* 效率问题，后面会进行一些效率上的优化（第一版功能实现后就一直没时间做这事，看来最近得找个时间做下了）。
* RichText解析的线程是**调用线程**，并不一定要是主线程，之所以这样做的目的就是为了适应开发者的各种需求把是否异步和如何异步的决定权交出去。
* 在展示大量元素的场景下（例如ListView、RecyclerView）不建议展示很长的富文本（甚至可以设置不显示图片），长富文本应该在单独的页面展示。

> 图片需要提前占位处理，并且图片的大小和展示的大小  

这个建议我会在下个版本中加入

感谢你的反馈
