### ISSUE TITLE
显示图片报错

### ISSUE THREAD

**Issue by findvoid** [zzhoujay/RichText#87]
<img width="688" alt="qq20161207-0 2x" src="https://cloud.githubusercontent.com/assets/13435914/20950158/f45db74e-bc58-11e6-9b1b-30ae065dbc73.png">

**Comment by zzhoujay** [comment]
OK，找到问题了，会在下个版本修复，感谢反馈

**Comment by chenwulue** [comment]
我也遇到了 2.3.0版本

**Comment by zzhoujay** [comment]
试试`2.3.2`版本吧，应该是修复了
