### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by findvoid** [zzhoujay/RichText#88]
<img width="391" alt="qq20161207-0 2x" src="https://cloud.githubusercontent.com/assets/13435914/20953348/d89418a4-bc6d-11e6-8f13-87298ee247c5.png">

**Comment by zzhoujay** [comment]
额，是匿名内部类引用了外部类导致的，把匿名OnImageClickListener对象换成静态的就好了

非静态内部类持有外部类引用会导致内存泄漏，以后注意下就好了
