### ISSUE TITLE
长图加载不出来

### ISSUE THREAD

**Issue by chenwulue** [zzhoujay/RichText#90]
有10M
 http://api.res.mojing.com//forum//20161212//C5960679B637350D5D4925EEC84C66FC.png 
不好意思不是我要发车的。。。

需要关闭硬件加速才能显示，但是那样应用就会变得很卡了。。

**Comment by zzhoujay** [comment]
额，我试了下我这边都能显示，你那边不能显示能不能把ImageFixCallback的FAILED回调中的exception打印下，看看是啥问题

**Comment by chenwulue** [comment]
Bitmap too large to be uploaded into a texture (540x7683, max=4096x4096)
Exception为null 这个就是大图的问题了吧

**Comment by zzhoujay** [comment]
大图的话，你可以在SIZE_READY那轮回调里给holder设置setMaxImageWidth和height来限制加载到内存的大小，你这张图是因为高度太大，你设置下maxImageHeight试下

**Comment by chenwulue** [comment]
哪有SIZE_READY的回调啊，我在ImageFixCallback的onFix里，设置了
` holder.setSize(400,400);
                        holder.setImageSize(400,400);`
照样显示不了

**Comment by zzhoujay** [comment]
是设置maxWidth和maxHeight，这两个属性是可以影响图片加载到内存的大小，image size和size只能改变图片显示的大小，你再试试吧

**Comment by chenwulue** [comment]
嗯，可以了，太模糊了，我看看要怎么调这个参数..

**Comment by zzhoujay** [comment]
会根据maxHeight和maxWidth来对图片进行缩放，而且加载到内存的图片的尺寸宽高都不会大于你设置的maxHeight和maxWidth，长图的话你可以先设置个较低的大小，然后点击后用一个单独的Activity来展示这个图片
