### ISSUE TITLE
图片加载高度被压缩 显示不完整

### ISSUE THREAD

**Issue by yizuochengchi** [zzhoujay/RichText#96]
您好 我用的是你一年前的 用Picasson加载图片的RichText 但是出现图片被压缩 和遮挡文字的问题 谢谢~

**Comment by zzhoujay** [comment]
现在还是用的去年的那个版本么？试试最新的版本吧

**Comment by yizuochengchi** [comment]
嗯 用了新的 加载图片没问题 但是 我想请教一下 你之前用的是picasso 为什么换gilde了呢？ picasso 不能满足部分需求吗?

**Comment by zzhoujay** [comment]
是为了加载Gif图片才换成Glide的，不过现在已经把图片加载器单独抽离出来了，默认使用的图片加载器是直接用okhttp来下载的图片，Glide的图片加载器不包含在RichText库里了，详情看下[wiki](https://github.com/zzhoujay/RichText/wiki/自定义图片加载器)吧，后面可能再添加个使用Picasso的图片加载器

**Comment by yizuochengchi** [comment]
我用picasso解决了这个问题 哈哈 还需要转换一下

**Comment by zzhoujay** [comment]
好的
