### ISSUE TITLE
recyclerview或者listview解析，会在每个item后面加padding

### ISSUE THREAD

**Issue by yxyaxng** [zzhoujay/RichText#99]
[padding数据.txt](https://github.com/zzhoujay/RichText/files/684011/padding.txt)

**Comment by zzhoujay** [comment]
测试了下，好像是因为P标签的问题，系统自带的Html解析器在遇到P标签后会添加几个换行

**Comment by yxyaxng** [comment]
怎么去解决这个换行呀，这个换行很影响美观呀

**Comment by zzhoujay** [comment]
目前只能不用P标签了，等后面我自定义个Html解析器才能控制这些

**Comment by ValuesFeng** [comment]
是否支持css呢？
